package errors

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Error) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "c":
			z.Code, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "Code")
				return
			}
		case "m":
			z.Msg, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Msg")
				return
			}
		case "d":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Data")
					return
				}
				z.Data = nil
			} else {
				z.Data, err = dc.ReadBytes(z.Data)
				if err != nil {
					err = msgp.WrapError(err, "Data")
					return
				}
				if z.Data == nil {
					z.Data = make([]byte, 0)
				}
			}
		case "t":
			z.TraceID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "TraceID")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Error) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "c"
	err = en.Append(0x84, 0xa1, 0x63)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Code)
	if err != nil {
		err = msgp.WrapError(err, "Code")
		return
	}
	// write "m"
	err = en.Append(0xa1, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteString(z.Msg)
	if err != nil {
		err = msgp.WrapError(err, "Msg")
		return
	}
	// write "d"
	err = en.Append(0xa1, 0x64)
	if err != nil {
		return
	}
	if z.Data == nil { // allownil: if nil
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteBytes(z.Data)
		if err != nil {
			err = msgp.WrapError(err, "Data")
			return
		}
	}
	// write "t"
	err = en.Append(0xa1, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.TraceID)
	if err != nil {
		err = msgp.WrapError(err, "TraceID")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Error) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "c"
	o = append(o, 0x84, 0xa1, 0x63)
	o = msgp.AppendUint16(o, z.Code)
	// string "m"
	o = append(o, 0xa1, 0x6d)
	o = msgp.AppendString(o, z.Msg)
	// string "d"
	o = append(o, 0xa1, 0x64)
	if z.Data == nil { // allownil: if nil
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendBytes(o, z.Data)
	}
	// string "t"
	o = append(o, 0xa1, 0x74)
	o = msgp.AppendString(o, z.TraceID)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Error) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "c":
			z.Code, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Code")
				return
			}
		case "m":
			z.Msg, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Msg")
				return
			}
		case "d":
			if msgp.IsNil(bts) {
				bts = bts[1:]
				z.Data = nil
			} else {
				z.Data, bts, err = msgp.ReadBytesBytes(bts, z.Data)
				if err != nil {
					err = msgp.WrapError(err, "Data")
					return
				}
				if z.Data == nil {
					z.Data = make([]byte, 0)
				}
			}
		case "t":
			z.TraceID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TraceID")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Error) Msgsize() (s int) {
	s = 1 + 2 + msgp.Uint16Size + 2 + msgp.StringPrefixSize + len(z.Msg) + 2 + msgp.BytesPrefixSize + len(z.Data) + 2 + msgp.StringPrefixSize + len(z.TraceID)
	return
}
