// Code generated by gencrpcclientv3. DO NOT EDIT.
package comm

import (
	"context"

	"github.com/ndsky1003/crpc/v3/client"
	"github.com/ndsky1003/crpc/v3/example/dto"
)

// CtxOnly invokes client3.MyService.CtxOnly
func CtxOnly(ctx context.Context, opts ...*client.Option) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = nil

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var resPtr any = nil

	// 修正 _ := 语法错误。如果不需要 error，使用 _ = 忽略
	_ = Default_lient.Call(ctx, "client3", "MyService.CtxOnly", reqBody, resPtr, opts...)

	// 3. 处理返回值
	// 无返回值
	return
}

// CtxReqPtr invokes client3.MyService.CtxReqPtr
func CtxReqPtr(ctx context.Context, req *dto.Req, opts ...*client.Option) (*dto.Res, error) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.Res
	var resPtr any = &res

	// 修正 _ := 语法错误。如果不需要 error，使用 _ = 忽略
	err := Default_lient.Call(ctx, "client3", "MyService.CtxReqPtr", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return &res, err
}

// CtxReqVal invokes client3.MyService.CtxReqVal
func CtxReqVal(ctx context.Context, req string, opts ...*client.Option) (string, error) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res string
	var resPtr any = &res

	// 修正 _ := 语法错误。如果不需要 error，使用 _ = 忽略
	err := Default_lient.Call(ctx, "client3", "MyService.CtxReqVal", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return res, err
}

// Empty invokes client3.MyService.Empty
func Empty(opts ...*client.Option) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = nil

	// Ctx 处理
	ctx := context.Background()

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var resPtr any = nil

	// 修正 _ := 语法错误。如果不需要 error，使用 _ = 忽略
	_ = Default_lient.Call(ctx, "client3", "MyService.Empty", reqBody, resPtr, opts...)

	// 3. 处理返回值
	// 无返回值
	return
}

// ErrOnly invokes client3.MyService.ErrOnly
func ErrOnly(req *dto.Req, opts ...*client.Option) error {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理
	ctx := context.Background()

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var resPtr any = nil

	// 修正 _ := 语法错误。如果不需要 error，使用 _ = 忽略
	err := Default_lient.Call(ctx, "client3", "MyService.ErrOnly", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return err
}

// Full invokes client3.MyService.Full
func Full(ctx context.Context, meta *dto.Meta, req *dto.Req, opts ...*client.Option) (*dto.Res, error) {
	// Meta 处理 (放入 opts)
	opts = append(opts, client.Options().SetMeta(meta))

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.Res
	var resPtr any = &res

	// 修正 _ := 语法错误。如果不需要 error，使用 _ = 忽略
	err := Default_lient.Call(ctx, "client3", "MyService.Full", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return &res, err
}

// MetaReq invokes client3.MyService.MetaReq
func MetaReq(meta *dto.Meta, req *dto.Req, opts ...*client.Option) (*dto.Res, error) {
	// Meta 处理 (放入 opts)
	opts = append(opts, client.Options().SetMeta(meta))

	// Req 处理
	var reqBody any = req

	// Ctx 处理
	ctx := context.Background()

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.Res
	var resPtr any = &res

	// 修正 _ := 语法错误。如果不需要 error，使用 _ = 忽略
	err := Default_lient.Call(ctx, "client3", "MyService.MetaReq", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return &res, err
}

// NoReturn invokes client3.MyService.NoReturn
func NoReturn(req *dto.Req, opts ...*client.Option) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理
	ctx := context.Background()

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var resPtr any = nil

	// 修正 _ := 语法错误。如果不需要 error，使用 _ = 忽略
	_ = Default_lient.Call(ctx, "client3", "MyService.NoReturn", reqBody, resPtr, opts...)

	// 3. 处理返回值
	// 无返回值
	return
}

// ReqOnly invokes client3.MyService.ReqOnly
func ReqOnly(req *dto.Req, opts ...*client.Option) (*dto.Res, error) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理
	ctx := context.Background()

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.Res
	var resPtr any = &res

	// 修正 _ := 语法错误。如果不需要 error，使用 _ = 忽略
	err := Default_lient.Call(ctx, "client3", "MyService.ReqOnly", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return &res, err
}

// ResOnly invokes client3.MyService.ResOnly
func ResOnly(req *dto.Req, opts ...*client.Option) *dto.Res {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理
	ctx := context.Background()

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.Res
	var resPtr any = &res

	// 修正 _ := 语法错误。如果不需要 error，使用 _ = 忽略
	_ = Default_lient.Call(ctx, "client3", "MyService.ResOnly", reqBody, resPtr, opts...)

	// 3. 处理返回值
	// 只有返回值，忽略错误
	return &res
}
