// Code generated by gencrpcclientv3. DO NOT EDIT.
package comm

import (
	"context"

	"github.com/ndsky1003/crpc/v3/client"
	"github.com/ndsky1003/crpc/v3/example/dto"
)

// BatchQuery invokes client3.BusinessService.BatchQuery
func BatchQuery(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) (*dto.BusinessRes, error) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.BusinessRes
	var resPtr any = &res

	// 【修正】强制捕获 error
	err := Default_Client.Call(ctx, "client3", "BusinessService.BatchQuery", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return &res, err
}

// BatchQuery_Go invokes client3.BusinessService.BatchQuery
func BatchQuery_Go(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) *client.Call {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Go 模式：异步调用，返回 Call 对象
	var res dto.BusinessRes
	return Default_Client.Go(ctx, "client3", "BusinessService.BatchQuery", reqBody, &res, opts...)
}

// BatchQuery_Send invokes client3.BusinessService.BatchQuery
func BatchQuery_Send(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) error {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Send 模式：单向发送
	return Default_Client.Send(ctx, "client3", "BusinessService.BatchQuery", reqBody, opts...)
}

// CreateOrder invokes client3.BusinessService.CreateOrder
func CreateOrder(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) (*dto.BusinessRes, error) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.BusinessRes
	var resPtr any = &res

	// 【修正】强制捕获 error
	err := Default_Client.Call(ctx, "client3", "BusinessService.CreateOrder", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return &res, err
}

// CreateOrder_Go invokes client3.BusinessService.CreateOrder
func CreateOrder_Go(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) *client.Call {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Go 模式：异步调用，返回 Call 对象
	var res dto.BusinessRes
	return Default_Client.Go(ctx, "client3", "BusinessService.CreateOrder", reqBody, &res, opts...)
}

// CreateOrder_Send invokes client3.BusinessService.CreateOrder
func CreateOrder_Send(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) error {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Send 模式：单向发送
	return Default_Client.Send(ctx, "client3", "BusinessService.CreateOrder", reqBody, opts...)
}

// GetCart invokes client3.BusinessService.GetCart
func GetCart(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) (*dto.BusinessRes, error) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.BusinessRes
	var resPtr any = &res

	// 【修正】强制捕获 error
	err := Default_Client.Call(ctx, "client3", "BusinessService.GetCart", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return &res, err
}

// GetCart_Go invokes client3.BusinessService.GetCart
func GetCart_Go(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) *client.Call {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Go 模式：异步调用，返回 Call 对象
	var res dto.BusinessRes
	return Default_Client.Go(ctx, "client3", "BusinessService.GetCart", reqBody, &res, opts...)
}

// GetCart_Send invokes client3.BusinessService.GetCart
func GetCart_Send(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) error {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Send 模式：单向发送
	return Default_Client.Send(ctx, "client3", "BusinessService.GetCart", reqBody, opts...)
}

// GetProductDetail invokes client3.BusinessService.GetProductDetail
func GetProductDetail(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) (*dto.BusinessRes, error) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.BusinessRes
	var resPtr any = &res

	// 【修正】强制捕获 error
	err := Default_Client.Call(ctx, "client3", "BusinessService.GetProductDetail", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return &res, err
}

// GetProductDetail_Go invokes client3.BusinessService.GetProductDetail
func GetProductDetail_Go(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) *client.Call {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Go 模式：异步调用，返回 Call 对象
	var res dto.BusinessRes
	return Default_Client.Go(ctx, "client3", "BusinessService.GetProductDetail", reqBody, &res, opts...)
}

// GetProductDetail_Send invokes client3.BusinessService.GetProductDetail
func GetProductDetail_Send(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) error {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Send 模式：单向发送
	return Default_Client.Send(ctx, "client3", "BusinessService.GetProductDetail", reqBody, opts...)
}

// QueryOrders invokes client3.BusinessService.QueryOrders
func QueryOrders(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) (*dto.BusinessRes, error) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.BusinessRes
	var resPtr any = &res

	// 【修正】强制捕获 error
	err := Default_Client.Call(ctx, "client3", "BusinessService.QueryOrders", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return &res, err
}

// QueryOrders_Go invokes client3.BusinessService.QueryOrders
func QueryOrders_Go(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) *client.Call {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Go 模式：异步调用，返回 Call 对象
	var res dto.BusinessRes
	return Default_Client.Go(ctx, "client3", "BusinessService.QueryOrders", reqBody, &res, opts...)
}

// QueryOrders_Send invokes client3.BusinessService.QueryOrders
func QueryOrders_Send(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) error {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Send 模式：单向发送
	return Default_Client.Send(ctx, "client3", "BusinessService.QueryOrders", reqBody, opts...)
}

// QueryUser invokes client3.BusinessService.QueryUser
func QueryUser(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) (*dto.BusinessRes, error) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.BusinessRes
	var resPtr any = &res

	// 【修正】强制捕获 error
	err := Default_Client.Call(ctx, "client3", "BusinessService.QueryUser", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return &res, err
}

// QueryUser_Go invokes client3.BusinessService.QueryUser
func QueryUser_Go(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) *client.Call {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Go 模式：异步调用，返回 Call 对象
	var res dto.BusinessRes
	return Default_Client.Go(ctx, "client3", "BusinessService.QueryUser", reqBody, &res, opts...)
}

// QueryUser_Send invokes client3.BusinessService.QueryUser
func QueryUser_Send(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) error {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Send 模式：单向发送
	return Default_Client.Send(ctx, "client3", "BusinessService.QueryUser", reqBody, opts...)
}

// SearchProducts invokes client3.BusinessService.SearchProducts
func SearchProducts(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) (*dto.BusinessRes, error) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.BusinessRes
	var resPtr any = &res

	// 【修正】强制捕获 error
	err := Default_Client.Call(ctx, "client3", "BusinessService.SearchProducts", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return &res, err
}

// SearchProducts_Go invokes client3.BusinessService.SearchProducts
func SearchProducts_Go(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) *client.Call {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Go 模式：异步调用，返回 Call 对象
	var res dto.BusinessRes
	return Default_Client.Go(ctx, "client3", "BusinessService.SearchProducts", reqBody, &res, opts...)
}

// SearchProducts_Send invokes client3.BusinessService.SearchProducts
func SearchProducts_Send(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) error {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Send 模式：单向发送
	return Default_Client.Send(ctx, "client3", "BusinessService.SearchProducts", reqBody, opts...)
}

// UpdateCart invokes client3.BusinessService.UpdateCart
func UpdateCart(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) (*dto.BusinessRes, error) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.BusinessRes
	var resPtr any = &res

	// 【修正】强制捕获 error
	err := Default_Client.Call(ctx, "client3", "BusinessService.UpdateCart", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return &res, err
}

// UpdateCart_Go invokes client3.BusinessService.UpdateCart
func UpdateCart_Go(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) *client.Call {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Go 模式：异步调用，返回 Call 对象
	var res dto.BusinessRes
	return Default_Client.Go(ctx, "client3", "BusinessService.UpdateCart", reqBody, &res, opts...)
}

// UpdateCart_Send invokes client3.BusinessService.UpdateCart
func UpdateCart_Send(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) error {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Send 模式：单向发送
	return Default_Client.Send(ctx, "client3", "BusinessService.UpdateCart", reqBody, opts...)
}

// UpdateUser invokes client3.BusinessService.UpdateUser
func UpdateUser(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) (*dto.BusinessRes, error) {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Call 模式：同步等待
	var res dto.BusinessRes
	var resPtr any = &res

	// 【修正】强制捕获 error
	err := Default_Client.Call(ctx, "client3", "BusinessService.UpdateUser", reqBody, resPtr, opts...)

	// 3. 处理返回值
	return &res, err
}

// UpdateUser_Go invokes client3.BusinessService.UpdateUser
func UpdateUser_Go(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) *client.Call {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Go 模式：异步调用，返回 Call 对象
	var res dto.BusinessRes
	return Default_Client.Go(ctx, "client3", "BusinessService.UpdateUser", reqBody, &res, opts...)
}

// UpdateUser_Send invokes client3.BusinessService.UpdateUser
func UpdateUser_Send(ctx context.Context, req *dto.BusinessReq, opts ...*client.Option) error {
	// Meta 处理 (放入 opts)

	// Req 处理
	var reqBody any = req

	// Ctx 处理

	// 2. 根据 CallType 分发调用
	// Send 模式：单向发送
	return Default_Client.Send(ctx, "client3", "BusinessService.UpdateUser", reqBody, opts...)
}
