package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
	"text/template"
)

// 参数定义
var (
	filePath   = flag.String("f", "", "source file path (e.g., ./msg_game.go)")
	structName = flag.String("s", "", "struct name to generate (e.g., msg_game)")
	output     = flag.String("o", "", "output file name (default: stdout)")
)

// 方法元数据
type MethodInfo struct {
	Name      string
	HasCtx    bool
	MetaType  string // e.g., "*Meta" or empty
	ReqType   string // e.g., "*PlayerInfoReq"
	ResType   string // e.g., "*PlayerInfoRes" or empty
	IsPointer bool   // Req is pointer?
	HasReturn bool   // Has return value (other than error)
}

func main() {
	flag.Parse()
	if *filePath == "" || *structName == "" {
		flag.Usage()
		return
	}

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, *filePath, nil, parser.ParseComments)
	if err != nil {
		log.Fatal(err)
	}

	methods := []MethodInfo{}
	packageName := node.Name.Name

	// 遍历 AST
	ast.Inspect(node, func(n ast.Node) bool {
		fn, ok := n.(*ast.FuncDecl)
		if !ok || fn.Recv == nil {
			return true
		}

		// 检查接收者是否是目标结构体
		recvType := ""
		switch t := fn.Recv.List[0].Type.(type) {
		case *ast.StarExpr:
			if ident, ok := t.X.(*ast.Ident); ok {
				recvType = ident.Name
			}
		case *ast.Ident:
			recvType = t.Name
		}

		if recvType != *structName {
			return true
		}

		if !fn.Name.IsExported() {
			return true
		}

		// 忽略 HandleMsg 自身，防止重复生成
		if fn.Name.Name == "HandleMsg" {
			return true
		}

		info := analyzeMethod(fn)
		methods = append(methods, info)
		return true
	})

	// 生成代码
	code := generateCode(packageName, *structName, methods)

	if *output != "" {
		os.WriteFile(*output, code, 0644)
	} else {
		fmt.Println(string(code))
	}
}

func analyzeMethod(fn *ast.FuncDecl) MethodInfo {
	info := MethodInfo{Name: fn.Name.Name}

	// 分析参数
	for _, field := range fn.Type.Params.List {
		typeStr := exprToString(field.Type)

		// 1. Context Check
		if strings.Contains(typeStr, "Context") {
			info.HasCtx = true
			continue
		}

		// 2. Meta Check (简单启发式：名字叫 meta 或者类型里包含 Meta)
		// 如果只有一个参数，那肯定是 Req，不是 Meta
		isMeta := false
		if len(field.Names) > 0 && strings.ToLower(field.Names[0].Name) == "meta" {
			isMeta = true
		}
		if !isMeta && strings.Contains(typeStr, "Meta") {
			// 只有当参数大于1个时，才尝试把包含 Meta 的类型认作 Meta
			// 否则如果请求体叫 MetadataReq 就会误判
			if info.ReqType == "" { // 还没找到 Req，暂且认为是 Meta?
				// 这里比较 tricky，严格来说应该看是否只有两个 struct 参数
			}
			isMeta = true
		}

		// 如果已经是 Req 了，那这个肯定不是 Meta
		if info.ReqType != "" {
			isMeta = false
		}

		if isMeta && info.MetaType == "" {
			info.MetaType = typeStr
		} else {
			// 默认为 Request
			info.ReqType = typeStr
			if _, ok := field.Type.(*ast.StarExpr); ok {
				info.IsPointer = true
			}
		}
	}

	// 修正：如果只有一个参数，且被误判为 Meta，强制改为 Req
	if info.ReqType == "" && info.MetaType != "" {
		info.ReqType = info.MetaType
		info.MetaType = ""
	}

	// 分析返回值
	if fn.Type.Results != nil {
		for _, field := range fn.Type.Results.List {
			typeStr := exprToString(field.Type)
			if typeStr != "error" {
				info.ResType = typeStr
				info.HasReturn = true
			}
		}
	}

	return info
}

func exprToString(expr ast.Expr) string {
	var buf bytes.Buffer
	format.Node(&buf, token.NewFileSet(), expr)
	return buf.String()
}

func generateCode(pkg, strct string, methods []MethodInfo) []byte {
	tpl := `// Code generated by gencrpcserverv3. DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"errors"
	"github.com/ndsky1003/crpc/v3/coder"
)

func (c *{{.Struct}}) HandleMsg(ctx context.Context, method string, metaCoderT coder.T, reqCoderT coder.T, metaBytes, bodyBytes []byte) (any, error) {
	switch method {
	{{- range .Methods}}
	case "{{.Name}}":
		var req {{.ReqTypeClean}}
		{{- if .HasCtx }}
		// ctx is passed from arguments
		{{- end}}
		
		{{- if .MetaType}}
		var meta {{.MetaTypeClean}}
		{{- end}}

		if err := coder.Unmarshal(reqCoderT, bodyBytes, &req); err != nil {
			return nil, err
		}
		{{- if .MetaType}}
		if len(metaBytes) > 0 {
			if err := coder.Unmarshal(metaCoderT, metaBytes, &meta); err != nil {
				return nil, err
			}
		}
		{{- end}}

		return c.{{.Name}}(
			{{- if .HasCtx}}ctx, {{end}}
			{{- if .MetaType}}{{if isPointer .MetaType}}&{{end}}meta, {{end}}
			{{if isPointer .ReqType}}&{{end}}req,
		)
	{{- end}}
	default:
		return nil, errors.New("unknown method: " + method)
	}
}
`

	// 辅助函数：清理类型字符串（去除 *）以便 new
	funcMap := template.FuncMap{
		"ReqTypeClean": func(m MethodInfo) string {
			return strings.TrimPrefix(m.ReqType, "*")
		},
		"MetaTypeClean": func(m MethodInfo) string {
			return strings.TrimPrefix(m.MetaType, "*")
		},
		"isPointer": func(t string) bool {
			return strings.HasPrefix(t, "*")
		},
	}

	t := template.Must(template.New("server").Funcs(funcMap).Parse(tpl))
	var buf bytes.Buffer
	err := t.Execute(&buf, map[string]interface{}{
		"Package": pkg,
		"Struct":  strct,
		"Methods": methods,
	})
	if err != nil {
		log.Fatal(err)
	}

	// 格式化代码
	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Println(buf.String()) // 打印出错的代码以便调试
		log.Fatal("format error:", err)
	}
	return src
}
