package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

// CLI 参数定义
var (
	suffix        string
	file_path     string
	out_file_name string
	out_dir       string
)

func init() {
	flag.StringVar(&suffix, "s", "_crpc_server_gen", "生成文件的后缀")
	flag.StringVar(&file_path, "f", "", "源文件路径")
	flag.StringVar(&out_file_name, "o", "", "输出文件名（可选）")
	flag.StringVar(&out_dir, "out_dir", "", "输出目录（可选）")
}

// MethodInfo 存储方法的元数据
type MethodInfo struct {
	Name      string
	HasCtx    bool
	MetaType  string // e.g., "*Meta" or empty
	ReqType   string // e.g., "*PlayerInfoReq"
	ResType   string // e.g., "*PlayerInfoRes" or empty
	IsPointer bool   // Req is pointer?
	HasReturn bool   // True if returns (Res, error), False if returns (error)
}

// StructInfo 存储结构体及其对应的方法
type StructInfo struct {
	Name    string
	Methods []MethodInfo
}

func main() {
	flag.Parse()

	// --- 路径处理逻辑 (集成您提供的代码) ---
	if file_path == "" {
		dir, err := os.Getwd()
		if err != nil {
			panic(err)
		}
		filename := os.Getenv("GOFILE")
		if filename == "" {
			// 如果不是 go generate 调用且没传参，直接返回不报错
			return
		}
		file_path = filepath.Join(dir, filename)
	}

	if file_path == "" {
		flag.Usage()
		return
	}

	dir, filename := filepath.Split(file_path)
	if !strings.HasSuffix(filename, ".go") {
		panic("源文件后缀必须是 .go")
	}

	if out_dir == "" {
		out_dir = dir
	}

	filenameBase := filename[:len(filename)-3]
	filename_new := fmt.Sprintf("%s%s.go", filenameBase, suffix)
	if out_file_name != "" {
		filename_new = out_file_name
	}

	out_file_path := filepath.Join(out_dir, filename_new)
	// ----------------------------------------

	// 解析 AST
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, file_path, nil, parser.ParseComments)
	if err != nil {
		log.Fatalf("Parse file error: %v", err)
	}

	packageName := node.Name.Name
	structMap := make(map[string][]MethodInfo)

	// 遍历 AST
	ast.Inspect(node, func(n ast.Node) bool {
		fn, ok := n.(*ast.FuncDecl)
		if !ok || fn.Recv == nil {
			return true
		}

		// 获取接收者类型名称
		recvType := ""
		switch t := fn.Recv.List[0].Type.(type) {
		case *ast.StarExpr:
			if ident, ok := t.X.(*ast.Ident); ok {
				recvType = ident.Name
			}
		case *ast.Ident:
			recvType = t.Name
		}

		if recvType == "" {
			return true
		}

		// 忽略未导出方法和 HandleMsg 自身
		if !fn.Name.IsExported() || fn.Name.Name == "HandleMsg" {
			return true
		}

		// 分析方法签名
		info, isValid := analyzeMethod(fn)
		if isValid {
			structMap[recvType] = append(structMap[recvType], info)
		}
		return true
	})

	// 排序保证生成稳定性
	var structs []StructInfo
	for name, methods := range structMap {
		structs = append(structs, StructInfo{
			Name:    name,
			Methods: methods,
		})
	}
	sort.Slice(structs, func(i, j int) bool {
		return structs[i].Name < structs[j].Name
	})

	if len(structs) == 0 {
		fmt.Println("// No suitable methods found.")
		return
	}

	// 生成代码
	code := generateCode(packageName, structs)

	// 写入文件
	if err := os.WriteFile(out_file_path, code, 0644); err != nil {
		log.Fatalf("Write file error: %v", err)
	}
}

// analyzeMethod 分析函数签名是否符合 RPC 要求
func analyzeMethod(fn *ast.FuncDecl) (MethodInfo, bool) {
	info := MethodInfo{Name: fn.Name.Name}

	// 1. 分析返回值
	if fn.Type.Results == nil || len(fn.Type.Results.List) == 0 {
		return info, false
	}
	results := fn.Type.Results.List
	if len(results) > 2 {
		return info, false
	}

	// 最后一个返回值必须是 error
	lastResult := results[len(results)-1]
	if exprToString(lastResult.Type) != "error" {
		return info, false
	}

	if len(results) == 2 {
		info.HasReturn = true // (Res, error)
		info.ResType = exprToString(results[0].Type)
	} else {
		info.HasReturn = false // (error)
	}

	// 2. 分析参数
	params := fn.Type.Params.List
	args := make([]*ast.Field, 0, len(params))
	for _, p := range params {
		if len(p.Names) > 1 {
			for range p.Names {
				args = append(args, p)
			}
		} else {
			args = append(args, p)
		}
	}

	if len(args) == 0 {
		return info, false
	}

	// 检查 Context
	firstType := exprToString(args[0].Type)
	if strings.Contains(firstType, "Context") {
		info.HasCtx = true
		args = args[1:]
	}

	if len(args) == 0 || len(args) > 2 {
		return info, false
	}

	if len(args) == 2 {
		// [Meta, Req]
		info.MetaType = exprToString(args[0].Type)
		info.ReqType = exprToString(args[1].Type)
		if _, ok := args[1].Type.(*ast.StarExpr); ok {
			info.IsPointer = true
		}
	} else if len(args) == 1 {
		// [Req]
		info.ReqType = exprToString(args[0].Type)
		if _, ok := args[0].Type.(*ast.StarExpr); ok {
			info.IsPointer = true
		}
	}

	return info, true
}

func exprToString(expr ast.Expr) string {
	var buf bytes.Buffer
	format.Node(&buf, token.NewFileSet(), expr)
	return buf.String()
}

func generateCode(pkg string, structs []StructInfo) []byte {
	tpl := `// Code generated by gencrpcserverv3. DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"errors"
	"github.com/ndsky1003/crpc/v3/coder"
)

{{- range .Structs}}

func (c *{{.Name}}) HandleMsg(ctx context.Context, method string, metaCoderT coder.T, reqCoderT coder.T, metaBytes, bodyBytes []byte) (any, error) {
	switch method {
	{{- range .Methods}}
	case "{{.Name}}":
		var req {{ReqTypeClean .}}
		{{- if .MetaType}}
		var meta {{MetaTypeClean .}}
		{{- end}}
		if err := coder.Unmarshal(reqCoderT, bodyBytes, &req); err != nil {
			return nil, err
		}
		{{- if .MetaType}}
		if len(metaBytes) > 0 {
			if err := coder.Unmarshal(metaCoderT, metaBytes, &meta); err != nil {
				return nil, err
			}
		}
		{{- end}}

		{{- if .HasReturn}}
		return c.{{.Name}}(
			{{- if .HasCtx}}ctx, {{end}}
			{{- if .MetaType}}{{if isPointer .MetaType}}&{{end}}meta, {{end}}
			{{- if isPointer .ReqType}}&{{end}}req,
		)
		{{- else}}
		return nil, c.{{.Name}}(
			{{- if .HasCtx}}ctx, {{end}}
			{{- if .MetaType}}{{if isPointer .MetaType}}&{{end}}meta, {{end}}
			{{- if isPointer .ReqType}}&{{end}}req,
		)
		{{- end}}
	{{- end}}
	default:
		return nil, errors.New("unknown method: " + method)
	}
}
{{- end}}
`

	funcMap := template.FuncMap{
		"ReqTypeClean": func(m MethodInfo) string {
			return strings.TrimPrefix(m.ReqType, "*")
		},
		"MetaTypeClean": func(m MethodInfo) string {
			return strings.TrimPrefix(m.MetaType, "*")
		},
		"isPointer": func(t string) bool {
			return strings.HasPrefix(t, "*")
		},
	}

	t := template.Must(template.New("server").Funcs(funcMap).Parse(tpl))
	var buf bytes.Buffer
	err := t.Execute(&buf, map[string]interface{}{
		"Package": pkg,
		"Structs": structs,
	})
	if err != nil {
		log.Fatalf("Template execute error: %v", err)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Println(buf.String())
		log.Fatalf("Format error: %v", err)
	}
	return src
}
