package dto

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *BusinessReq) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "user_info":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "UserInfo")
					return
				}
				z.UserInfo = nil
			} else {
				if z.UserInfo == nil {
					z.UserInfo = new(UserInfo)
				}
				err = z.UserInfo.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "UserInfo")
					return
				}
			}
		case "order_info":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "OrderInfo")
					return
				}
				z.OrderInfo = nil
			} else {
				if z.OrderInfo == nil {
					z.OrderInfo = new(OrderInfo)
				}
				err = z.OrderInfo.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "OrderInfo")
					return
				}
			}
		case "products":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Products")
				return
			}
			if cap(z.Products) >= int(zb0002) {
				z.Products = (z.Products)[:zb0002]
			} else {
				z.Products = make([]*ProductInfo, zb0002)
			}
			for za0001 := range z.Products {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Products", za0001)
						return
					}
					z.Products[za0001] = nil
				} else {
					if z.Products[za0001] == nil {
						z.Products[za0001] = new(ProductInfo)
					}
					err = z.Products[za0001].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Products", za0001)
						return
					}
				}
			}
		case "cart_info":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "CartInfo")
					return
				}
				z.CartInfo = nil
			} else {
				if z.CartInfo == nil {
					z.CartInfo = new(CartInfo)
				}
				err = z.CartInfo.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "CartInfo")
					return
				}
			}
		case "query_param":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "QueryParam")
					return
				}
				z.QueryParam = nil
			} else {
				if z.QueryParam == nil {
					z.QueryParam = new(QueryParam)
				}
				err = z.QueryParam.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "QueryParam")
					return
				}
			}
		case "request_id":
			z.RequestID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "RequestID")
				return
			}
		case "trace_id":
			z.TraceID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "TraceID")
				return
			}
		case "client_type":
			z.ClientType, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ClientType")
				return
			}
		case "version":
			z.Version, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "timestamp":
			z.Timestamp, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *BusinessReq) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(10)
	var zb0001Mask uint16 /* 10 bits */
	_ = zb0001Mask
	if z.UserInfo == nil {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.OrderInfo == nil {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Products == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.CartInfo == nil {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.QueryParam == nil {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// write "user_info"
			err = en.Append(0xa9, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f)
			if err != nil {
				return
			}
			if z.UserInfo == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.UserInfo.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "UserInfo")
					return
				}
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "order_info"
			err = en.Append(0xaa, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f)
			if err != nil {
				return
			}
			if z.OrderInfo == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.OrderInfo.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "OrderInfo")
					return
				}
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "products"
			err = en.Append(0xa8, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.Products)))
			if err != nil {
				err = msgp.WrapError(err, "Products")
				return
			}
			for za0001 := range z.Products {
				if z.Products[za0001] == nil {
					err = en.WriteNil()
					if err != nil {
						return
					}
				} else {
					err = z.Products[za0001].EncodeMsg(en)
					if err != nil {
						err = msgp.WrapError(err, "Products", za0001)
						return
					}
				}
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "cart_info"
			err = en.Append(0xa9, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f)
			if err != nil {
				return
			}
			if z.CartInfo == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.CartInfo.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "CartInfo")
					return
				}
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "query_param"
			err = en.Append(0xab, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d)
			if err != nil {
				return
			}
			if z.QueryParam == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.QueryParam.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "QueryParam")
					return
				}
			}
		}
		// write "request_id"
		err = en.Append(0xaa, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64)
		if err != nil {
			return
		}
		err = en.WriteString(z.RequestID)
		if err != nil {
			err = msgp.WrapError(err, "RequestID")
			return
		}
		// write "trace_id"
		err = en.Append(0xa8, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64)
		if err != nil {
			return
		}
		err = en.WriteString(z.TraceID)
		if err != nil {
			err = msgp.WrapError(err, "TraceID")
			return
		}
		// write "client_type"
		err = en.Append(0xab, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.ClientType)
		if err != nil {
			err = msgp.WrapError(err, "ClientType")
			return
		}
		// write "version"
		err = en.Append(0xa7, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
		if err != nil {
			return
		}
		err = en.WriteString(z.Version)
		if err != nil {
			err = msgp.WrapError(err, "Version")
			return
		}
		// write "timestamp"
		err = en.Append(0xa9, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
		if err != nil {
			return
		}
		err = en.WriteInt64(z.Timestamp)
		if err != nil {
			err = msgp.WrapError(err, "Timestamp")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *BusinessReq) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(10)
	var zb0001Mask uint16 /* 10 bits */
	_ = zb0001Mask
	if z.UserInfo == nil {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.OrderInfo == nil {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Products == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.CartInfo == nil {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.QueryParam == nil {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// string "user_info"
			o = append(o, 0xa9, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f)
			if z.UserInfo == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.UserInfo.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "UserInfo")
					return
				}
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "order_info"
			o = append(o, 0xaa, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f)
			if z.OrderInfo == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.OrderInfo.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "OrderInfo")
					return
				}
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "products"
			o = append(o, 0xa8, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73)
			o = msgp.AppendArrayHeader(o, uint32(len(z.Products)))
			for za0001 := range z.Products {
				if z.Products[za0001] == nil {
					o = msgp.AppendNil(o)
				} else {
					o, err = z.Products[za0001].MarshalMsg(o)
					if err != nil {
						err = msgp.WrapError(err, "Products", za0001)
						return
					}
				}
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "cart_info"
			o = append(o, 0xa9, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f)
			if z.CartInfo == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.CartInfo.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "CartInfo")
					return
				}
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "query_param"
			o = append(o, 0xab, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d)
			if z.QueryParam == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.QueryParam.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "QueryParam")
					return
				}
			}
		}
		// string "request_id"
		o = append(o, 0xaa, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64)
		o = msgp.AppendString(o, z.RequestID)
		// string "trace_id"
		o = append(o, 0xa8, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64)
		o = msgp.AppendString(o, z.TraceID)
		// string "client_type"
		o = append(o, 0xab, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65)
		o = msgp.AppendString(o, z.ClientType)
		// string "version"
		o = append(o, 0xa7, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
		o = msgp.AppendString(o, z.Version)
		// string "timestamp"
		o = append(o, 0xa9, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
		o = msgp.AppendInt64(o, z.Timestamp)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *BusinessReq) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "user_info":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.UserInfo = nil
			} else {
				if z.UserInfo == nil {
					z.UserInfo = new(UserInfo)
				}
				bts, err = z.UserInfo.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "UserInfo")
					return
				}
			}
		case "order_info":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.OrderInfo = nil
			} else {
				if z.OrderInfo == nil {
					z.OrderInfo = new(OrderInfo)
				}
				bts, err = z.OrderInfo.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "OrderInfo")
					return
				}
			}
		case "products":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Products")
				return
			}
			if cap(z.Products) >= int(zb0002) {
				z.Products = (z.Products)[:zb0002]
			} else {
				z.Products = make([]*ProductInfo, zb0002)
			}
			for za0001 := range z.Products {
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					z.Products[za0001] = nil
				} else {
					if z.Products[za0001] == nil {
						z.Products[za0001] = new(ProductInfo)
					}
					bts, err = z.Products[za0001].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Products", za0001)
						return
					}
				}
			}
		case "cart_info":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.CartInfo = nil
			} else {
				if z.CartInfo == nil {
					z.CartInfo = new(CartInfo)
				}
				bts, err = z.CartInfo.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "CartInfo")
					return
				}
			}
		case "query_param":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.QueryParam = nil
			} else {
				if z.QueryParam == nil {
					z.QueryParam = new(QueryParam)
				}
				bts, err = z.QueryParam.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "QueryParam")
					return
				}
			}
		case "request_id":
			z.RequestID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RequestID")
				return
			}
		case "trace_id":
			z.TraceID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TraceID")
				return
			}
		case "client_type":
			z.ClientType, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ClientType")
				return
			}
		case "version":
			z.Version, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "timestamp":
			z.Timestamp, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *BusinessReq) Msgsize() (s int) {
	s = 1 + 10
	if z.UserInfo == nil {
		s += msgp.NilSize
	} else {
		s += z.UserInfo.Msgsize()
	}
	s += 11
	if z.OrderInfo == nil {
		s += msgp.NilSize
	} else {
		s += z.OrderInfo.Msgsize()
	}
	s += 9 + msgp.ArrayHeaderSize
	for za0001 := range z.Products {
		if z.Products[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.Products[za0001].Msgsize()
		}
	}
	s += 10
	if z.CartInfo == nil {
		s += msgp.NilSize
	} else {
		s += z.CartInfo.Msgsize()
	}
	s += 12
	if z.QueryParam == nil {
		s += msgp.NilSize
	} else {
		s += z.QueryParam.Msgsize()
	}
	s += 11 + msgp.StringPrefixSize + len(z.RequestID) + 9 + msgp.StringPrefixSize + len(z.TraceID) + 12 + msgp.StringPrefixSize + len(z.ClientType) + 8 + msgp.StringPrefixSize + len(z.Version) + 10 + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *BusinessRes) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "user_info":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "UserInfo")
					return
				}
				z.UserInfo = nil
			} else {
				if z.UserInfo == nil {
					z.UserInfo = new(UserInfo)
				}
				err = z.UserInfo.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "UserInfo")
					return
				}
			}
		case "order_info":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "OrderInfo")
					return
				}
				z.OrderInfo = nil
			} else {
				if z.OrderInfo == nil {
					z.OrderInfo = new(OrderInfo)
				}
				err = z.OrderInfo.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "OrderInfo")
					return
				}
			}
		case "products":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Products")
				return
			}
			if cap(z.Products) >= int(zb0002) {
				z.Products = (z.Products)[:zb0002]
			} else {
				z.Products = make([]*ProductInfo, zb0002)
			}
			for za0001 := range z.Products {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Products", za0001)
						return
					}
					z.Products[za0001] = nil
				} else {
					if z.Products[za0001] == nil {
						z.Products[za0001] = new(ProductInfo)
					}
					err = z.Products[za0001].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Products", za0001)
						return
					}
				}
			}
		case "cart_info":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "CartInfo")
					return
				}
				z.CartInfo = nil
			} else {
				if z.CartInfo == nil {
					z.CartInfo = new(CartInfo)
				}
				err = z.CartInfo.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "CartInfo")
					return
				}
			}
		case "orders":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Orders")
				return
			}
			if cap(z.Orders) >= int(zb0003) {
				z.Orders = (z.Orders)[:zb0003]
			} else {
				z.Orders = make([]*OrderInfo, zb0003)
			}
			for za0002 := range z.Orders {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Orders", za0002)
						return
					}
					z.Orders[za0002] = nil
				} else {
					if z.Orders[za0002] == nil {
						z.Orders[za0002] = new(OrderInfo)
					}
					err = z.Orders[za0002].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Orders", za0002)
						return
					}
				}
			}
		case "total_count":
			z.TotalCount, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "TotalCount")
				return
			}
		case "page_num":
			z.PageNum, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "PageNum")
				return
			}
		case "page_size":
			z.PageSize, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "PageSize")
				return
			}
		case "code":
			z.Code, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Code")
				return
			}
		case "message":
			z.Message, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Message")
				return
			}
		case "success":
			z.Success, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Success")
				return
			}
		case "request_id":
			z.RequestID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "RequestID")
				return
			}
		case "timestamp":
			z.Timestamp, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "trace_id":
			z.TraceID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "TraceID")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *BusinessRes) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(14)
	var zb0001Mask uint16 /* 14 bits */
	_ = zb0001Mask
	if z.UserInfo == nil {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.OrderInfo == nil {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Products == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.CartInfo == nil {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Orders == nil {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// write "user_info"
			err = en.Append(0xa9, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f)
			if err != nil {
				return
			}
			if z.UserInfo == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.UserInfo.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "UserInfo")
					return
				}
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "order_info"
			err = en.Append(0xaa, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f)
			if err != nil {
				return
			}
			if z.OrderInfo == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.OrderInfo.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "OrderInfo")
					return
				}
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "products"
			err = en.Append(0xa8, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.Products)))
			if err != nil {
				err = msgp.WrapError(err, "Products")
				return
			}
			for za0001 := range z.Products {
				if z.Products[za0001] == nil {
					err = en.WriteNil()
					if err != nil {
						return
					}
				} else {
					err = z.Products[za0001].EncodeMsg(en)
					if err != nil {
						err = msgp.WrapError(err, "Products", za0001)
						return
					}
				}
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "cart_info"
			err = en.Append(0xa9, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f)
			if err != nil {
				return
			}
			if z.CartInfo == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.CartInfo.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "CartInfo")
					return
				}
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "orders"
			err = en.Append(0xa6, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.Orders)))
			if err != nil {
				err = msgp.WrapError(err, "Orders")
				return
			}
			for za0002 := range z.Orders {
				if z.Orders[za0002] == nil {
					err = en.WriteNil()
					if err != nil {
						return
					}
				} else {
					err = z.Orders[za0002].EncodeMsg(en)
					if err != nil {
						err = msgp.WrapError(err, "Orders", za0002)
						return
					}
				}
			}
		}
		// write "total_count"
		err = en.Append(0xab, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74)
		if err != nil {
			return
		}
		err = en.WriteInt64(z.TotalCount)
		if err != nil {
			err = msgp.WrapError(err, "TotalCount")
			return
		}
		// write "page_num"
		err = en.Append(0xa8, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d)
		if err != nil {
			return
		}
		err = en.WriteInt32(z.PageNum)
		if err != nil {
			err = msgp.WrapError(err, "PageNum")
			return
		}
		// write "page_size"
		err = en.Append(0xa9, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65)
		if err != nil {
			return
		}
		err = en.WriteInt32(z.PageSize)
		if err != nil {
			err = msgp.WrapError(err, "PageSize")
			return
		}
		// write "code"
		err = en.Append(0xa4, 0x63, 0x6f, 0x64, 0x65)
		if err != nil {
			return
		}
		err = en.WriteInt32(z.Code)
		if err != nil {
			err = msgp.WrapError(err, "Code")
			return
		}
		// write "message"
		err = en.Append(0xa7, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.Message)
		if err != nil {
			err = msgp.WrapError(err, "Message")
			return
		}
		// write "success"
		err = en.Append(0xa7, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73)
		if err != nil {
			return
		}
		err = en.WriteBool(z.Success)
		if err != nil {
			err = msgp.WrapError(err, "Success")
			return
		}
		// write "request_id"
		err = en.Append(0xaa, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64)
		if err != nil {
			return
		}
		err = en.WriteString(z.RequestID)
		if err != nil {
			err = msgp.WrapError(err, "RequestID")
			return
		}
		// write "timestamp"
		err = en.Append(0xa9, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
		if err != nil {
			return
		}
		err = en.WriteInt64(z.Timestamp)
		if err != nil {
			err = msgp.WrapError(err, "Timestamp")
			return
		}
		// write "trace_id"
		err = en.Append(0xa8, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64)
		if err != nil {
			return
		}
		err = en.WriteString(z.TraceID)
		if err != nil {
			err = msgp.WrapError(err, "TraceID")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *BusinessRes) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(14)
	var zb0001Mask uint16 /* 14 bits */
	_ = zb0001Mask
	if z.UserInfo == nil {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.OrderInfo == nil {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Products == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.CartInfo == nil {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Orders == nil {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// string "user_info"
			o = append(o, 0xa9, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f)
			if z.UserInfo == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.UserInfo.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "UserInfo")
					return
				}
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "order_info"
			o = append(o, 0xaa, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f)
			if z.OrderInfo == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.OrderInfo.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "OrderInfo")
					return
				}
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "products"
			o = append(o, 0xa8, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73)
			o = msgp.AppendArrayHeader(o, uint32(len(z.Products)))
			for za0001 := range z.Products {
				if z.Products[za0001] == nil {
					o = msgp.AppendNil(o)
				} else {
					o, err = z.Products[za0001].MarshalMsg(o)
					if err != nil {
						err = msgp.WrapError(err, "Products", za0001)
						return
					}
				}
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "cart_info"
			o = append(o, 0xa9, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f)
			if z.CartInfo == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.CartInfo.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "CartInfo")
					return
				}
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "orders"
			o = append(o, 0xa6, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73)
			o = msgp.AppendArrayHeader(o, uint32(len(z.Orders)))
			for za0002 := range z.Orders {
				if z.Orders[za0002] == nil {
					o = msgp.AppendNil(o)
				} else {
					o, err = z.Orders[za0002].MarshalMsg(o)
					if err != nil {
						err = msgp.WrapError(err, "Orders", za0002)
						return
					}
				}
			}
		}
		// string "total_count"
		o = append(o, 0xab, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74)
		o = msgp.AppendInt64(o, z.TotalCount)
		// string "page_num"
		o = append(o, 0xa8, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d)
		o = msgp.AppendInt32(o, z.PageNum)
		// string "page_size"
		o = append(o, 0xa9, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65)
		o = msgp.AppendInt32(o, z.PageSize)
		// string "code"
		o = append(o, 0xa4, 0x63, 0x6f, 0x64, 0x65)
		o = msgp.AppendInt32(o, z.Code)
		// string "message"
		o = append(o, 0xa7, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65)
		o = msgp.AppendString(o, z.Message)
		// string "success"
		o = append(o, 0xa7, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73)
		o = msgp.AppendBool(o, z.Success)
		// string "request_id"
		o = append(o, 0xaa, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64)
		o = msgp.AppendString(o, z.RequestID)
		// string "timestamp"
		o = append(o, 0xa9, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
		o = msgp.AppendInt64(o, z.Timestamp)
		// string "trace_id"
		o = append(o, 0xa8, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64)
		o = msgp.AppendString(o, z.TraceID)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *BusinessRes) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "user_info":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.UserInfo = nil
			} else {
				if z.UserInfo == nil {
					z.UserInfo = new(UserInfo)
				}
				bts, err = z.UserInfo.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "UserInfo")
					return
				}
			}
		case "order_info":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.OrderInfo = nil
			} else {
				if z.OrderInfo == nil {
					z.OrderInfo = new(OrderInfo)
				}
				bts, err = z.OrderInfo.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "OrderInfo")
					return
				}
			}
		case "products":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Products")
				return
			}
			if cap(z.Products) >= int(zb0002) {
				z.Products = (z.Products)[:zb0002]
			} else {
				z.Products = make([]*ProductInfo, zb0002)
			}
			for za0001 := range z.Products {
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					z.Products[za0001] = nil
				} else {
					if z.Products[za0001] == nil {
						z.Products[za0001] = new(ProductInfo)
					}
					bts, err = z.Products[za0001].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Products", za0001)
						return
					}
				}
			}
		case "cart_info":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.CartInfo = nil
			} else {
				if z.CartInfo == nil {
					z.CartInfo = new(CartInfo)
				}
				bts, err = z.CartInfo.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "CartInfo")
					return
				}
			}
		case "orders":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Orders")
				return
			}
			if cap(z.Orders) >= int(zb0003) {
				z.Orders = (z.Orders)[:zb0003]
			} else {
				z.Orders = make([]*OrderInfo, zb0003)
			}
			for za0002 := range z.Orders {
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					z.Orders[za0002] = nil
				} else {
					if z.Orders[za0002] == nil {
						z.Orders[za0002] = new(OrderInfo)
					}
					bts, err = z.Orders[za0002].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Orders", za0002)
						return
					}
				}
			}
		case "total_count":
			z.TotalCount, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalCount")
				return
			}
		case "page_num":
			z.PageNum, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PageNum")
				return
			}
		case "page_size":
			z.PageSize, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PageSize")
				return
			}
		case "code":
			z.Code, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Code")
				return
			}
		case "message":
			z.Message, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Message")
				return
			}
		case "success":
			z.Success, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Success")
				return
			}
		case "request_id":
			z.RequestID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RequestID")
				return
			}
		case "timestamp":
			z.Timestamp, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "trace_id":
			z.TraceID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TraceID")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *BusinessRes) Msgsize() (s int) {
	s = 1 + 10
	if z.UserInfo == nil {
		s += msgp.NilSize
	} else {
		s += z.UserInfo.Msgsize()
	}
	s += 11
	if z.OrderInfo == nil {
		s += msgp.NilSize
	} else {
		s += z.OrderInfo.Msgsize()
	}
	s += 9 + msgp.ArrayHeaderSize
	for za0001 := range z.Products {
		if z.Products[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.Products[za0001].Msgsize()
		}
	}
	s += 10
	if z.CartInfo == nil {
		s += msgp.NilSize
	} else {
		s += z.CartInfo.Msgsize()
	}
	s += 7 + msgp.ArrayHeaderSize
	for za0002 := range z.Orders {
		if z.Orders[za0002] == nil {
			s += msgp.NilSize
		} else {
			s += z.Orders[za0002].Msgsize()
		}
	}
	s += 12 + msgp.Int64Size + 9 + msgp.Int32Size + 10 + msgp.Int32Size + 5 + msgp.Int32Size + 8 + msgp.StringPrefixSize + len(z.Message) + 8 + msgp.BoolSize + 11 + msgp.StringPrefixSize + len(z.RequestID) + 10 + msgp.Int64Size + 9 + msgp.StringPrefixSize + len(z.TraceID)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CartInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "cart_id":
			z.CartID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "CartID")
				return
			}
		case "user_id":
			z.UserID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
		case "items":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Items")
				return
			}
			if cap(z.Items) >= int(zb0002) {
				z.Items = (z.Items)[:zb0002]
			} else {
				z.Items = make([]CartItemInfo, zb0002)
			}
			for za0001 := range z.Items {
				err = z.Items[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Items", za0001)
					return
				}
			}
		case "total_amount":
			z.TotalAmount, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "TotalAmount")
				return
			}
		case "update_time":
			z.UpdateTime, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "UpdateTime")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CartInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "cart_id"
	err = en.Append(0x85, 0xa7, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.CartID)
	if err != nil {
		err = msgp.WrapError(err, "CartID")
		return
	}
	// write "user_id"
	err = en.Append(0xa7, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.UserID)
	if err != nil {
		err = msgp.WrapError(err, "UserID")
		return
	}
	// write "items"
	err = en.Append(0xa5, 0x69, 0x74, 0x65, 0x6d, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Items)))
	if err != nil {
		err = msgp.WrapError(err, "Items")
		return
	}
	for za0001 := range z.Items {
		err = z.Items[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Items", za0001)
			return
		}
	}
	// write "total_amount"
	err = en.Append(0xac, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.TotalAmount)
	if err != nil {
		err = msgp.WrapError(err, "TotalAmount")
		return
	}
	// write "update_time"
	err = en.Append(0xab, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteTime(z.UpdateTime)
	if err != nil {
		err = msgp.WrapError(err, "UpdateTime")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CartInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "cart_id"
	o = append(o, 0x85, 0xa7, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.CartID)
	// string "user_id"
	o = append(o, 0xa7, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.UserID)
	// string "items"
	o = append(o, 0xa5, 0x69, 0x74, 0x65, 0x6d, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Items)))
	for za0001 := range z.Items {
		o, err = z.Items[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Items", za0001)
			return
		}
	}
	// string "total_amount"
	o = append(o, 0xac, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendFloat64(o, z.TotalAmount)
	// string "update_time"
	o = append(o, 0xab, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	o = msgp.AppendTime(o, z.UpdateTime)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CartInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "cart_id":
			z.CartID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CartID")
				return
			}
		case "user_id":
			z.UserID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
		case "items":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Items")
				return
			}
			if cap(z.Items) >= int(zb0002) {
				z.Items = (z.Items)[:zb0002]
			} else {
				z.Items = make([]CartItemInfo, zb0002)
			}
			for za0001 := range z.Items {
				bts, err = z.Items[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Items", za0001)
					return
				}
			}
		case "total_amount":
			z.TotalAmount, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalAmount")
				return
			}
		case "update_time":
			z.UpdateTime, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdateTime")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CartInfo) Msgsize() (s int) {
	s = 1 + 8 + msgp.StringPrefixSize + len(z.CartID) + 8 + msgp.StringPrefixSize + len(z.UserID) + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Items {
		s += z.Items[za0001].Msgsize()
	}
	s += 13 + msgp.Float64Size + 12 + msgp.TimeSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CartItemInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "product_id":
			z.ProductID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ProductID")
				return
			}
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "price":
			z.Price, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Price")
				return
			}
		case "quantity":
			z.Quantity, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Quantity")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CartItemInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "product_id"
	err = en.Append(0x84, 0xaa, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ProductID)
	if err != nil {
		err = msgp.WrapError(err, "ProductID")
		return
	}
	// write "name"
	err = en.Append(0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "price"
	err = en.Append(0xa5, 0x70, 0x72, 0x69, 0x63, 0x65)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Price)
	if err != nil {
		err = msgp.WrapError(err, "Price")
		return
	}
	// write "quantity"
	err = en.Append(0xa8, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Quantity)
	if err != nil {
		err = msgp.WrapError(err, "Quantity")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CartItemInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "product_id"
	o = append(o, 0x84, 0xaa, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.ProductID)
	// string "name"
	o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "price"
	o = append(o, 0xa5, 0x70, 0x72, 0x69, 0x63, 0x65)
	o = msgp.AppendFloat64(o, z.Price)
	// string "quantity"
	o = append(o, 0xa8, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79)
	o = msgp.AppendInt32(o, z.Quantity)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CartItemInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "product_id":
			z.ProductID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ProductID")
				return
			}
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "price":
			z.Price, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Price")
				return
			}
		case "quantity":
			z.Quantity, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Quantity")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CartItemInfo) Msgsize() (s int) {
	s = 1 + 11 + msgp.StringPrefixSize + len(z.ProductID) + 5 + msgp.StringPrefixSize + len(z.Name) + 6 + msgp.Float64Size + 9 + msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *OrderInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "order_id":
			z.OrderID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "OrderID")
				return
			}
		case "user_id":
			z.UserID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
		case "order_no":
			z.OrderNo, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "OrderNo")
				return
			}
		case "total_amount":
			z.TotalAmount, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "TotalAmount")
				return
			}
		case "pay_amount":
			z.PayAmount, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "PayAmount")
				return
			}
		case "discount_amount":
			z.DiscountAmount, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "DiscountAmount")
				return
			}
		case "status":
			z.Status, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "pay_method":
			z.PayMethod, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PayMethod")
				return
			}
		case "pay_time":
			z.PayTime, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "PayTime")
				return
			}
		case "delivery_addr":
			z.DeliveryAddr, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "DeliveryAddr")
				return
			}
		case "remark":
			z.Remark, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Remark")
				return
			}
		case "create_time":
			z.CreateTime, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "CreateTime")
				return
			}
		case "update_time":
			z.UpdateTime, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "UpdateTime")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *OrderInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 13
	// write "order_id"
	err = en.Append(0x8d, 0xa8, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.OrderID)
	if err != nil {
		err = msgp.WrapError(err, "OrderID")
		return
	}
	// write "user_id"
	err = en.Append(0xa7, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.UserID)
	if err != nil {
		err = msgp.WrapError(err, "UserID")
		return
	}
	// write "order_no"
	err = en.Append(0xa8, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteString(z.OrderNo)
	if err != nil {
		err = msgp.WrapError(err, "OrderNo")
		return
	}
	// write "total_amount"
	err = en.Append(0xac, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.TotalAmount)
	if err != nil {
		err = msgp.WrapError(err, "TotalAmount")
		return
	}
	// write "pay_amount"
	err = en.Append(0xaa, 0x70, 0x61, 0x79, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.PayAmount)
	if err != nil {
		err = msgp.WrapError(err, "PayAmount")
		return
	}
	// write "discount_amount"
	err = en.Append(0xaf, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.DiscountAmount)
	if err != nil {
		err = msgp.WrapError(err, "DiscountAmount")
		return
	}
	// write "status"
	err = en.Append(0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Status)
	if err != nil {
		err = msgp.WrapError(err, "Status")
		return
	}
	// write "pay_method"
	err = en.Append(0xaa, 0x70, 0x61, 0x79, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.PayMethod)
	if err != nil {
		err = msgp.WrapError(err, "PayMethod")
		return
	}
	// write "pay_time"
	err = en.Append(0xa8, 0x70, 0x61, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteTime(z.PayTime)
	if err != nil {
		err = msgp.WrapError(err, "PayTime")
		return
	}
	// write "delivery_addr"
	err = en.Append(0xad, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.DeliveryAddr)
	if err != nil {
		err = msgp.WrapError(err, "DeliveryAddr")
		return
	}
	// write "remark"
	err = en.Append(0xa6, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteString(z.Remark)
	if err != nil {
		err = msgp.WrapError(err, "Remark")
		return
	}
	// write "create_time"
	err = en.Append(0xab, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteTime(z.CreateTime)
	if err != nil {
		err = msgp.WrapError(err, "CreateTime")
		return
	}
	// write "update_time"
	err = en.Append(0xab, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteTime(z.UpdateTime)
	if err != nil {
		err = msgp.WrapError(err, "UpdateTime")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *OrderInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 13
	// string "order_id"
	o = append(o, 0x8d, 0xa8, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.OrderID)
	// string "user_id"
	o = append(o, 0xa7, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.UserID)
	// string "order_no"
	o = append(o, 0xa8, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f)
	o = msgp.AppendString(o, z.OrderNo)
	// string "total_amount"
	o = append(o, 0xac, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendFloat64(o, z.TotalAmount)
	// string "pay_amount"
	o = append(o, 0xaa, 0x70, 0x61, 0x79, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendFloat64(o, z.PayAmount)
	// string "discount_amount"
	o = append(o, 0xaf, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendFloat64(o, z.DiscountAmount)
	// string "status"
	o = append(o, 0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	o = msgp.AppendInt32(o, z.Status)
	// string "pay_method"
	o = append(o, 0xaa, 0x70, 0x61, 0x79, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64)
	o = msgp.AppendString(o, z.PayMethod)
	// string "pay_time"
	o = append(o, 0xa8, 0x70, 0x61, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	o = msgp.AppendTime(o, z.PayTime)
	// string "delivery_addr"
	o = append(o, 0xad, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72)
	o = msgp.AppendString(o, z.DeliveryAddr)
	// string "remark"
	o = append(o, 0xa6, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b)
	o = msgp.AppendString(o, z.Remark)
	// string "create_time"
	o = append(o, 0xab, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	o = msgp.AppendTime(o, z.CreateTime)
	// string "update_time"
	o = append(o, 0xab, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	o = msgp.AppendTime(o, z.UpdateTime)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *OrderInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "order_id":
			z.OrderID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "OrderID")
				return
			}
		case "user_id":
			z.UserID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
		case "order_no":
			z.OrderNo, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "OrderNo")
				return
			}
		case "total_amount":
			z.TotalAmount, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalAmount")
				return
			}
		case "pay_amount":
			z.PayAmount, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PayAmount")
				return
			}
		case "discount_amount":
			z.DiscountAmount, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DiscountAmount")
				return
			}
		case "status":
			z.Status, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "pay_method":
			z.PayMethod, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PayMethod")
				return
			}
		case "pay_time":
			z.PayTime, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PayTime")
				return
			}
		case "delivery_addr":
			z.DeliveryAddr, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DeliveryAddr")
				return
			}
		case "remark":
			z.Remark, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Remark")
				return
			}
		case "create_time":
			z.CreateTime, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreateTime")
				return
			}
		case "update_time":
			z.UpdateTime, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdateTime")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *OrderInfo) Msgsize() (s int) {
	s = 1 + 9 + msgp.StringPrefixSize + len(z.OrderID) + 8 + msgp.StringPrefixSize + len(z.UserID) + 9 + msgp.StringPrefixSize + len(z.OrderNo) + 13 + msgp.Float64Size + 11 + msgp.Float64Size + 16 + msgp.Float64Size + 7 + msgp.Int32Size + 11 + msgp.StringPrefixSize + len(z.PayMethod) + 9 + msgp.TimeSize + 14 + msgp.StringPrefixSize + len(z.DeliveryAddr) + 7 + msgp.StringPrefixSize + len(z.Remark) + 12 + msgp.TimeSize + 12 + msgp.TimeSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ProductInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "product_id":
			z.ProductID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ProductID")
				return
			}
		case "category_id":
			z.CategoryID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "CategoryID")
				return
			}
		case "name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "description":
			z.Description, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Description")
				return
			}
		case "price":
			z.Price, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Price")
				return
			}
		case "stock":
			z.Stock, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Stock")
				return
			}
		case "sales":
			z.Sales, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Sales")
				return
			}
		case "images":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Images")
				return
			}
			if cap(z.Images) >= int(zb0002) {
				z.Images = (z.Images)[:zb0002]
			} else {
				z.Images = make([]string, zb0002)
			}
			for za0001 := range z.Images {
				z.Images[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Images", za0001)
					return
				}
			}
		case "tags":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Tags")
				return
			}
			if cap(z.Tags) >= int(zb0003) {
				z.Tags = (z.Tags)[:zb0003]
			} else {
				z.Tags = make([]string, zb0003)
			}
			for za0002 := range z.Tags {
				z.Tags[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Tags", za0002)
					return
				}
			}
		case "create_time":
			z.CreateTime, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "CreateTime")
				return
			}
		case "update_time":
			z.UpdateTime, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "UpdateTime")
				return
			}
		case "is_active":
			z.IsActive, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "IsActive")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ProductInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 12
	// write "product_id"
	err = en.Append(0x8c, 0xaa, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.ProductID)
	if err != nil {
		err = msgp.WrapError(err, "ProductID")
		return
	}
	// write "category_id"
	err = en.Append(0xab, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.CategoryID)
	if err != nil {
		err = msgp.WrapError(err, "CategoryID")
		return
	}
	// write "name"
	err = en.Append(0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "description"
	err = en.Append(0xab, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Description)
	if err != nil {
		err = msgp.WrapError(err, "Description")
		return
	}
	// write "price"
	err = en.Append(0xa5, 0x70, 0x72, 0x69, 0x63, 0x65)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Price)
	if err != nil {
		err = msgp.WrapError(err, "Price")
		return
	}
	// write "stock"
	err = en.Append(0xa5, 0x73, 0x74, 0x6f, 0x63, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Stock)
	if err != nil {
		err = msgp.WrapError(err, "Stock")
		return
	}
	// write "sales"
	err = en.Append(0xa5, 0x73, 0x61, 0x6c, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Sales)
	if err != nil {
		err = msgp.WrapError(err, "Sales")
		return
	}
	// write "images"
	err = en.Append(0xa6, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Images)))
	if err != nil {
		err = msgp.WrapError(err, "Images")
		return
	}
	for za0001 := range z.Images {
		err = en.WriteString(z.Images[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Images", za0001)
			return
		}
	}
	// write "tags"
	err = en.Append(0xa4, 0x74, 0x61, 0x67, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Tags)))
	if err != nil {
		err = msgp.WrapError(err, "Tags")
		return
	}
	for za0002 := range z.Tags {
		err = en.WriteString(z.Tags[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Tags", za0002)
			return
		}
	}
	// write "create_time"
	err = en.Append(0xab, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteTime(z.CreateTime)
	if err != nil {
		err = msgp.WrapError(err, "CreateTime")
		return
	}
	// write "update_time"
	err = en.Append(0xab, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteTime(z.UpdateTime)
	if err != nil {
		err = msgp.WrapError(err, "UpdateTime")
		return
	}
	// write "is_active"
	err = en.Append(0xa9, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
	if err != nil {
		return
	}
	err = en.WriteBool(z.IsActive)
	if err != nil {
		err = msgp.WrapError(err, "IsActive")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ProductInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 12
	// string "product_id"
	o = append(o, 0x8c, 0xaa, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.ProductID)
	// string "category_id"
	o = append(o, 0xab, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.CategoryID)
	// string "name"
	o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "description"
	o = append(o, 0xab, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.Description)
	// string "price"
	o = append(o, 0xa5, 0x70, 0x72, 0x69, 0x63, 0x65)
	o = msgp.AppendFloat64(o, z.Price)
	// string "stock"
	o = append(o, 0xa5, 0x73, 0x74, 0x6f, 0x63, 0x6b)
	o = msgp.AppendInt32(o, z.Stock)
	// string "sales"
	o = append(o, 0xa5, 0x73, 0x61, 0x6c, 0x65, 0x73)
	o = msgp.AppendInt32(o, z.Sales)
	// string "images"
	o = append(o, 0xa6, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Images)))
	for za0001 := range z.Images {
		o = msgp.AppendString(o, z.Images[za0001])
	}
	// string "tags"
	o = append(o, 0xa4, 0x74, 0x61, 0x67, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Tags)))
	for za0002 := range z.Tags {
		o = msgp.AppendString(o, z.Tags[za0002])
	}
	// string "create_time"
	o = append(o, 0xab, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	o = msgp.AppendTime(o, z.CreateTime)
	// string "update_time"
	o = append(o, 0xab, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	o = msgp.AppendTime(o, z.UpdateTime)
	// string "is_active"
	o = append(o, 0xa9, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
	o = msgp.AppendBool(o, z.IsActive)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ProductInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "product_id":
			z.ProductID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ProductID")
				return
			}
		case "category_id":
			z.CategoryID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CategoryID")
				return
			}
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "description":
			z.Description, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Description")
				return
			}
		case "price":
			z.Price, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Price")
				return
			}
		case "stock":
			z.Stock, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Stock")
				return
			}
		case "sales":
			z.Sales, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Sales")
				return
			}
		case "images":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Images")
				return
			}
			if cap(z.Images) >= int(zb0002) {
				z.Images = (z.Images)[:zb0002]
			} else {
				z.Images = make([]string, zb0002)
			}
			for za0001 := range z.Images {
				z.Images[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Images", za0001)
					return
				}
			}
		case "tags":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Tags")
				return
			}
			if cap(z.Tags) >= int(zb0003) {
				z.Tags = (z.Tags)[:zb0003]
			} else {
				z.Tags = make([]string, zb0003)
			}
			for za0002 := range z.Tags {
				z.Tags[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Tags", za0002)
					return
				}
			}
		case "create_time":
			z.CreateTime, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreateTime")
				return
			}
		case "update_time":
			z.UpdateTime, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdateTime")
				return
			}
		case "is_active":
			z.IsActive, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IsActive")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ProductInfo) Msgsize() (s int) {
	s = 1 + 11 + msgp.StringPrefixSize + len(z.ProductID) + 12 + msgp.StringPrefixSize + len(z.CategoryID) + 5 + msgp.StringPrefixSize + len(z.Name) + 12 + msgp.StringPrefixSize + len(z.Description) + 6 + msgp.Float64Size + 6 + msgp.Int32Size + 6 + msgp.Int32Size + 7 + msgp.ArrayHeaderSize
	for za0001 := range z.Images {
		s += msgp.StringPrefixSize + len(z.Images[za0001])
	}
	s += 5 + msgp.ArrayHeaderSize
	for za0002 := range z.Tags {
		s += msgp.StringPrefixSize + len(z.Tags[za0002])
	}
	s += 12 + msgp.TimeSize + 12 + msgp.TimeSize + 10 + msgp.BoolSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *QueryParam) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "page_num":
			z.PageNum, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "PageNum")
				return
			}
		case "page_size":
			z.PageSize, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "PageSize")
				return
			}
		case "sort_by":
			z.SortBy, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SortBy")
				return
			}
		case "sort_order":
			z.SortOrder, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SortOrder")
				return
			}
		case "filters":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Filters")
				return
			}
			if z.Filters == nil {
				z.Filters = make(map[string]string, zb0002)
			} else if len(z.Filters) > 0 {
				for key := range z.Filters {
					delete(z.Filters, key)
				}
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				var za0002 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Filters")
					return
				}
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Filters", za0001)
					return
				}
				z.Filters[za0001] = za0002
			}
		case "keywords":
			z.Keywords, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Keywords")
				return
			}
		case "category_id":
			z.CategoryID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "CategoryID")
				return
			}
		case "price_min":
			z.PriceMin, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "PriceMin")
				return
			}
		case "price_max":
			z.PriceMax, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "PriceMax")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *QueryParam) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 9
	// write "page_num"
	err = en.Append(0x89, 0xa8, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.PageNum)
	if err != nil {
		err = msgp.WrapError(err, "PageNum")
		return
	}
	// write "page_size"
	err = en.Append(0xa9, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.PageSize)
	if err != nil {
		err = msgp.WrapError(err, "PageSize")
		return
	}
	// write "sort_by"
	err = en.Append(0xa7, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x62, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.SortBy)
	if err != nil {
		err = msgp.WrapError(err, "SortBy")
		return
	}
	// write "sort_order"
	err = en.Append(0xaa, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.SortOrder)
	if err != nil {
		err = msgp.WrapError(err, "SortOrder")
		return
	}
	// write "filters"
	err = en.Append(0xa7, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Filters)))
	if err != nil {
		err = msgp.WrapError(err, "Filters")
		return
	}
	for za0001, za0002 := range z.Filters {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Filters")
			return
		}
		err = en.WriteString(za0002)
		if err != nil {
			err = msgp.WrapError(err, "Filters", za0001)
			return
		}
	}
	// write "keywords"
	err = en.Append(0xa8, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.Keywords)
	if err != nil {
		err = msgp.WrapError(err, "Keywords")
		return
	}
	// write "category_id"
	err = en.Append(0xab, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.CategoryID)
	if err != nil {
		err = msgp.WrapError(err, "CategoryID")
		return
	}
	// write "price_min"
	err = en.Append(0xa9, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x69, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.PriceMin)
	if err != nil {
		err = msgp.WrapError(err, "PriceMin")
		return
	}
	// write "price_max"
	err = en.Append(0xa9, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x78)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.PriceMax)
	if err != nil {
		err = msgp.WrapError(err, "PriceMax")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *QueryParam) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 9
	// string "page_num"
	o = append(o, 0x89, 0xa8, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d)
	o = msgp.AppendInt32(o, z.PageNum)
	// string "page_size"
	o = append(o, 0xa9, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65)
	o = msgp.AppendInt32(o, z.PageSize)
	// string "sort_by"
	o = append(o, 0xa7, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x62, 0x79)
	o = msgp.AppendString(o, z.SortBy)
	// string "sort_order"
	o = append(o, 0xaa, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72)
	o = msgp.AppendString(o, z.SortOrder)
	// string "filters"
	o = append(o, 0xa7, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Filters)))
	for za0001, za0002 := range z.Filters {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendString(o, za0002)
	}
	// string "keywords"
	o = append(o, 0xa8, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73)
	o = msgp.AppendString(o, z.Keywords)
	// string "category_id"
	o = append(o, 0xab, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.CategoryID)
	// string "price_min"
	o = append(o, 0xa9, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x69, 0x6e)
	o = msgp.AppendFloat64(o, z.PriceMin)
	// string "price_max"
	o = append(o, 0xa9, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6d, 0x61, 0x78)
	o = msgp.AppendFloat64(o, z.PriceMax)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *QueryParam) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "page_num":
			z.PageNum, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PageNum")
				return
			}
		case "page_size":
			z.PageSize, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PageSize")
				return
			}
		case "sort_by":
			z.SortBy, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SortBy")
				return
			}
		case "sort_order":
			z.SortOrder, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SortOrder")
				return
			}
		case "filters":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Filters")
				return
			}
			if z.Filters == nil {
				z.Filters = make(map[string]string, zb0002)
			} else if len(z.Filters) > 0 {
				for key := range z.Filters {
					delete(z.Filters, key)
				}
			}
			for zb0002 > 0 {
				var za0001 string
				var za0002 string
				zb0002--
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Filters")
					return
				}
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Filters", za0001)
					return
				}
				z.Filters[za0001] = za0002
			}
		case "keywords":
			z.Keywords, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Keywords")
				return
			}
		case "category_id":
			z.CategoryID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CategoryID")
				return
			}
		case "price_min":
			z.PriceMin, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PriceMin")
				return
			}
		case "price_max":
			z.PriceMax, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PriceMax")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *QueryParam) Msgsize() (s int) {
	s = 1 + 9 + msgp.Int32Size + 10 + msgp.Int32Size + 8 + msgp.StringPrefixSize + len(z.SortBy) + 11 + msgp.StringPrefixSize + len(z.SortOrder) + 8 + msgp.MapHeaderSize
	if z.Filters != nil {
		for za0001, za0002 := range z.Filters {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.StringPrefixSize + len(za0002)
		}
	}
	s += 9 + msgp.StringPrefixSize + len(z.Keywords) + 12 + msgp.StringPrefixSize + len(z.CategoryID) + 10 + msgp.Float64Size + 10 + msgp.Float64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *UserInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "user_id":
			z.UserID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
		case "username":
			z.Username, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Username")
				return
			}
		case "email":
			z.Email, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Email")
				return
			}
		case "phone":
			z.Phone, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Phone")
				return
			}
		case "avatar":
			z.Avatar, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Avatar")
				return
			}
		case "create_time":
			z.CreateTime, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "CreateTime")
				return
			}
		case "update_time":
			z.UpdateTime, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "UpdateTime")
				return
			}
		case "status":
			z.Status, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "is_vip":
			z.IsVIP, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "IsVIP")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *UserInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 9
	// write "user_id"
	err = en.Append(0x89, 0xa7, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.UserID)
	if err != nil {
		err = msgp.WrapError(err, "UserID")
		return
	}
	// write "username"
	err = en.Append(0xa8, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Username)
	if err != nil {
		err = msgp.WrapError(err, "Username")
		return
	}
	// write "email"
	err = en.Append(0xa5, 0x65, 0x6d, 0x61, 0x69, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString(z.Email)
	if err != nil {
		err = msgp.WrapError(err, "Email")
		return
	}
	// write "phone"
	err = en.Append(0xa5, 0x70, 0x68, 0x6f, 0x6e, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Phone)
	if err != nil {
		err = msgp.WrapError(err, "Phone")
		return
	}
	// write "avatar"
	err = en.Append(0xa6, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.Avatar)
	if err != nil {
		err = msgp.WrapError(err, "Avatar")
		return
	}
	// write "create_time"
	err = en.Append(0xab, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteTime(z.CreateTime)
	if err != nil {
		err = msgp.WrapError(err, "CreateTime")
		return
	}
	// write "update_time"
	err = en.Append(0xab, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteTime(z.UpdateTime)
	if err != nil {
		err = msgp.WrapError(err, "UpdateTime")
		return
	}
	// write "status"
	err = en.Append(0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Status)
	if err != nil {
		err = msgp.WrapError(err, "Status")
		return
	}
	// write "is_vip"
	err = en.Append(0xa6, 0x69, 0x73, 0x5f, 0x76, 0x69, 0x70)
	if err != nil {
		return
	}
	err = en.WriteBool(z.IsVIP)
	if err != nil {
		err = msgp.WrapError(err, "IsVIP")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *UserInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 9
	// string "user_id"
	o = append(o, 0x89, 0xa7, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64)
	o = msgp.AppendString(o, z.UserID)
	// string "username"
	o = append(o, 0xa8, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Username)
	// string "email"
	o = append(o, 0xa5, 0x65, 0x6d, 0x61, 0x69, 0x6c)
	o = msgp.AppendString(o, z.Email)
	// string "phone"
	o = append(o, 0xa5, 0x70, 0x68, 0x6f, 0x6e, 0x65)
	o = msgp.AppendString(o, z.Phone)
	// string "avatar"
	o = append(o, 0xa6, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72)
	o = msgp.AppendString(o, z.Avatar)
	// string "create_time"
	o = append(o, 0xab, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	o = msgp.AppendTime(o, z.CreateTime)
	// string "update_time"
	o = append(o, 0xab, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65)
	o = msgp.AppendTime(o, z.UpdateTime)
	// string "status"
	o = append(o, 0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	o = msgp.AppendInt32(o, z.Status)
	// string "is_vip"
	o = append(o, 0xa6, 0x69, 0x73, 0x5f, 0x76, 0x69, 0x70)
	o = msgp.AppendBool(o, z.IsVIP)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *UserInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "user_id":
			z.UserID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
		case "username":
			z.Username, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Username")
				return
			}
		case "email":
			z.Email, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Email")
				return
			}
		case "phone":
			z.Phone, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Phone")
				return
			}
		case "avatar":
			z.Avatar, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Avatar")
				return
			}
		case "create_time":
			z.CreateTime, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreateTime")
				return
			}
		case "update_time":
			z.UpdateTime, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdateTime")
				return
			}
		case "status":
			z.Status, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "is_vip":
			z.IsVIP, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IsVIP")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *UserInfo) Msgsize() (s int) {
	s = 1 + 8 + msgp.StringPrefixSize + len(z.UserID) + 9 + msgp.StringPrefixSize + len(z.Username) + 6 + msgp.StringPrefixSize + len(z.Email) + 6 + msgp.StringPrefixSize + len(z.Phone) + 7 + msgp.StringPrefixSize + len(z.Avatar) + 12 + msgp.TimeSize + 12 + msgp.TimeSize + 7 + msgp.Int32Size + 7 + msgp.BoolSize
	return
}
