// Code generated by gencrpcserverv3. DO NOT EDIT.
package main

import (
	"context"
	"errors"

	"github.com/ndsky1003/crpc/v3/coder"
)

func (c *OrderService) HandleMsg(ctx context.Context, method string, metaCoderT coder.T, reqCoderT coder.T, metaData, bodyData any, fromNetwork bool) (any, error) {
	switch method {
	case "ProcessOrder":
		// 1. 准备 Req
		var req OrderReq

		if fromNetwork {
			// 远程调用 (Bytes)
			if b, ok := bodyData.([]byte); ok {
				if len(b) > 0 {
					if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
						return nil, err
					}
				}
			}
		} else {
			// 本地调用 (Object)
			if bodyData != nil {
				if v, ok := bodyData.(*OrderReq); ok {
					if v != nil {
						req = *v
					}
				} else if v, ok := bodyData.(OrderReq); ok {
					req = v
				} else {
					return nil, errors.New("local call type mismatch for ProcessOrder arg: req")
				}
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res, err := c.ProcessOrder(ctx, &req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	default:
		return nil, errors.New("unknown method: " + method)
	}
}
