package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
	"text/template"
)

var (
	filePath   = flag.String("f", "", "source file path")
	structName = flag.String("s", "", "service struct name (to read methods from)")
	output     = flag.String("o", "", "output file")
)

type MethodInfo struct {
	Name      string
	ReqType   string
	ResType   string
	MetaType  string
	HasReturn bool
}

func main() {
	flag.Parse()
	if *filePath == "" || *structName == "" {
		flag.Usage()
		return
	}

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, *filePath, nil, parser.ParseComments)
	if err != nil {
		log.Fatal(err)
	}

	packageName := node.Name.Name
	methods := []MethodInfo{}

	ast.Inspect(node, func(n ast.Node) bool {
		fn, ok := n.(*ast.FuncDecl)
		if !ok || fn.Recv == nil {
			return true
		}

		recvType := ""
		switch t := fn.Recv.List[0].Type.(type) {
		case *ast.StarExpr:
			if ident, ok := t.X.(*ast.Ident); ok {
				recvType = ident.Name
			}
		case *ast.Ident:
			recvType = t.Name
		}

		if recvType != *structName {
			return true
		}

		if !fn.Name.IsExported() || fn.Name.Name == "HandleMsg" {
			return true
		}

		info := MethodInfo{Name: fn.Name.Name}

		// 分析参数
		for _, p := range fn.Type.Params.List {
			t := exprToString(p.Type)
			if strings.Contains(t, "Context") {
				continue
			}
			if strings.Contains(t, "Meta") || (len(p.Names) > 0 && p.Names[0].Name == "meta") {
				info.MetaType = t
				continue
			}
			info.ReqType = t
		}

		// 分析返回值
		if fn.Type.Results != nil {
			for _, r := range fn.Type.Results.List {
				t := exprToString(r.Type)
				if t != "error" {
					info.ResType = t
					info.HasReturn = true
				}
			}
		}
		methods = append(methods, info)
		return true
	})

	code := generateClientCode(packageName, *structName, methods)
	if *output != "" {
		os.WriteFile(*output, code, 0644)
	} else {
		fmt.Println(string(code))
	}
}

func exprToString(expr ast.Expr) string {
	var buf bytes.Buffer
	format.Node(&buf, token.NewFileSet(), expr)
	return buf.String()
}

func generateClientCode(pkg, serviceName string, methods []MethodInfo) []byte {
	tpl := `// Code generated by gencrpcclientv3. DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"github.com/ndsky1003/crpc/v3/client"
)

type {{.Service}}Client struct {
	c *client.Client
	serviceName string
}

func New{{.Service}}Client(c *client.Client, serviceName string) *{{.Service}}Client {
	return &{{.Service}}Client{
		c: c,
		serviceName: serviceName,
	}
}

{{- range .Methods}}

func (c *{{$.Service}}Client) {{.Name}}(ctx context.Context, {{if .MetaType}}meta {{.MetaType}}, {{end}}req {{.ReqType}}, opts ...*client.Option) ({{if .HasReturn}}{{.ResType}}, {{end}}error) {
	{{- if .HasReturn}}
	var res {{.ResTypeClean}}
	{{- end}}
	
	// Prepare Options
	{{- if .MetaType}}
	opts = append(opts, client.Options().SetMeta(meta))
	{{- end}}

	err := c.c.Call(ctx, c.serviceName, "{{$.Service}}.{{.Name}}", req, {{if .HasReturn}}&res{{else}}nil{{end}}, opts...)
	{{- if .HasReturn}}
	return {{if isPointer .ResType}}res{{else}}*res{{end}}, err
	{{- else}}
	return err
	{{- end}}
}
{{- end}}
`

	funcMap := template.FuncMap{
		"ResTypeClean": func(m MethodInfo) string {
			return strings.TrimPrefix(m.ResType, "*")
		},
		"isPointer": func(t string) bool {
			return strings.HasPrefix(t, "*")
		},
	}

	t := template.Must(template.New("client").Funcs(funcMap).Parse(tpl))
	var buf bytes.Buffer
	err := t.Execute(&buf, map[string]interface{}{
		"Package": pkg,
		"Service": serviceName,
		"Methods": methods,
	})
	if err != nil {
		log.Fatal(err)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Println(buf.String())
		log.Fatal("format error:", err)
	}
	return src
}
