package main

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *OrderReq) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "oid":
			z.OrderID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "OrderID")
				return
			}
		case "uid":
			z.UserID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
		case "pids":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "ProductIDs")
				return
			}
			if cap(z.ProductIDs) >= int(zb0002) {
				z.ProductIDs = (z.ProductIDs)[:zb0002]
			} else {
				z.ProductIDs = make([]string, zb0002)
			}
			for za0001 := range z.ProductIDs {
				z.ProductIDs[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "ProductIDs", za0001)
					return
				}
			}
		case "amt":
			z.Amount, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Amount")
				return
			}
		case "status":
			z.Status, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "pay":
			z.PaymentType, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "PaymentType")
				return
			}
		case "recv":
			z.ReceiverInfo, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ReceiverInfo")
				return
			}
		case "ts":
			z.Timestamp, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "meta":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
			if cap(z.Metadata) >= int(zb0003) {
				z.Metadata = (z.Metadata)[:zb0003]
			} else {
				z.Metadata = make([]string, zb0003)
			}
			for za0002 := range z.Metadata {
				z.Metadata[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Metadata", za0002)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *OrderReq) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 9
	// write "oid"
	err = en.Append(0x89, 0xa3, 0x6f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.OrderID)
	if err != nil {
		err = msgp.WrapError(err, "OrderID")
		return
	}
	// write "uid"
	err = en.Append(0xa3, 0x75, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.UserID)
	if err != nil {
		err = msgp.WrapError(err, "UserID")
		return
	}
	// write "pids"
	err = en.Append(0xa4, 0x70, 0x69, 0x64, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.ProductIDs)))
	if err != nil {
		err = msgp.WrapError(err, "ProductIDs")
		return
	}
	for za0001 := range z.ProductIDs {
		err = en.WriteString(z.ProductIDs[za0001])
		if err != nil {
			err = msgp.WrapError(err, "ProductIDs", za0001)
			return
		}
	}
	// write "amt"
	err = en.Append(0xa3, 0x61, 0x6d, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Amount)
	if err != nil {
		err = msgp.WrapError(err, "Amount")
		return
	}
	// write "status"
	err = en.Append(0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.Status)
	if err != nil {
		err = msgp.WrapError(err, "Status")
		return
	}
	// write "pay"
	err = en.Append(0xa3, 0x70, 0x61, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.PaymentType)
	if err != nil {
		err = msgp.WrapError(err, "PaymentType")
		return
	}
	// write "recv"
	err = en.Append(0xa4, 0x72, 0x65, 0x63, 0x76)
	if err != nil {
		return
	}
	err = en.WriteString(z.ReceiverInfo)
	if err != nil {
		err = msgp.WrapError(err, "ReceiverInfo")
		return
	}
	// write "ts"
	err = en.Append(0xa2, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Timestamp)
	if err != nil {
		err = msgp.WrapError(err, "Timestamp")
		return
	}
	// write "meta"
	err = en.Append(0xa4, 0x6d, 0x65, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Metadata)))
	if err != nil {
		err = msgp.WrapError(err, "Metadata")
		return
	}
	for za0002 := range z.Metadata {
		err = en.WriteString(z.Metadata[za0002])
		if err != nil {
			err = msgp.WrapError(err, "Metadata", za0002)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *OrderReq) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 9
	// string "oid"
	o = append(o, 0x89, 0xa3, 0x6f, 0x69, 0x64)
	o = msgp.AppendString(o, z.OrderID)
	// string "uid"
	o = append(o, 0xa3, 0x75, 0x69, 0x64)
	o = msgp.AppendString(o, z.UserID)
	// string "pids"
	o = append(o, 0xa4, 0x70, 0x69, 0x64, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.ProductIDs)))
	for za0001 := range z.ProductIDs {
		o = msgp.AppendString(o, z.ProductIDs[za0001])
	}
	// string "amt"
	o = append(o, 0xa3, 0x61, 0x6d, 0x74)
	o = msgp.AppendInt64(o, z.Amount)
	// string "status"
	o = append(o, 0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	o = msgp.AppendString(o, z.Status)
	// string "pay"
	o = append(o, 0xa3, 0x70, 0x61, 0x79)
	o = msgp.AppendString(o, z.PaymentType)
	// string "recv"
	o = append(o, 0xa4, 0x72, 0x65, 0x63, 0x76)
	o = msgp.AppendString(o, z.ReceiverInfo)
	// string "ts"
	o = append(o, 0xa2, 0x74, 0x73)
	o = msgp.AppendInt64(o, z.Timestamp)
	// string "meta"
	o = append(o, 0xa4, 0x6d, 0x65, 0x74, 0x61)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Metadata)))
	for za0002 := range z.Metadata {
		o = msgp.AppendString(o, z.Metadata[za0002])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *OrderReq) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "oid":
			z.OrderID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "OrderID")
				return
			}
		case "uid":
			z.UserID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
		case "pids":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ProductIDs")
				return
			}
			if cap(z.ProductIDs) >= int(zb0002) {
				z.ProductIDs = (z.ProductIDs)[:zb0002]
			} else {
				z.ProductIDs = make([]string, zb0002)
			}
			for za0001 := range z.ProductIDs {
				z.ProductIDs[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ProductIDs", za0001)
					return
				}
			}
		case "amt":
			z.Amount, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Amount")
				return
			}
		case "status":
			z.Status, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "pay":
			z.PaymentType, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PaymentType")
				return
			}
		case "recv":
			z.ReceiverInfo, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ReceiverInfo")
				return
			}
		case "ts":
			z.Timestamp, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "meta":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Metadata")
				return
			}
			if cap(z.Metadata) >= int(zb0003) {
				z.Metadata = (z.Metadata)[:zb0003]
			} else {
				z.Metadata = make([]string, zb0003)
			}
			for za0002 := range z.Metadata {
				z.Metadata[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Metadata", za0002)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *OrderReq) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len(z.OrderID) + 4 + msgp.StringPrefixSize + len(z.UserID) + 5 + msgp.ArrayHeaderSize
	for za0001 := range z.ProductIDs {
		s += msgp.StringPrefixSize + len(z.ProductIDs[za0001])
	}
	s += 4 + msgp.Int64Size + 7 + msgp.StringPrefixSize + len(z.Status) + 4 + msgp.StringPrefixSize + len(z.PaymentType) + 5 + msgp.StringPrefixSize + len(z.ReceiverInfo) + 3 + msgp.Int64Size + 5 + msgp.ArrayHeaderSize
	for za0002 := range z.Metadata {
		s += msgp.StringPrefixSize + len(z.Metadata[za0002])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *OrderRes) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "oid":
			z.OrderID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "OrderID")
				return
			}
		case "f":
			z.From, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "From")
				return
			}
		case "status":
			z.Status, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "pat":
			z.ProcessedAt, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ProcessedAt")
				return
			}
		case "msg":
			z.Message, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Message")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *OrderRes) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "oid"
	err = en.Append(0x85, 0xa3, 0x6f, 0x69, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.OrderID)
	if err != nil {
		err = msgp.WrapError(err, "OrderID")
		return
	}
	// write "f"
	err = en.Append(0xa1, 0x66)
	if err != nil {
		return
	}
	err = en.WriteString(z.From)
	if err != nil {
		err = msgp.WrapError(err, "From")
		return
	}
	// write "status"
	err = en.Append(0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.Status)
	if err != nil {
		err = msgp.WrapError(err, "Status")
		return
	}
	// write "pat"
	err = en.Append(0xa3, 0x70, 0x61, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.ProcessedAt)
	if err != nil {
		err = msgp.WrapError(err, "ProcessedAt")
		return
	}
	// write "msg"
	err = en.Append(0xa3, 0x6d, 0x73, 0x67)
	if err != nil {
		return
	}
	err = en.WriteString(z.Message)
	if err != nil {
		err = msgp.WrapError(err, "Message")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *OrderRes) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "oid"
	o = append(o, 0x85, 0xa3, 0x6f, 0x69, 0x64)
	o = msgp.AppendString(o, z.OrderID)
	// string "f"
	o = append(o, 0xa1, 0x66)
	o = msgp.AppendString(o, z.From)
	// string "status"
	o = append(o, 0xa6, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73)
	o = msgp.AppendString(o, z.Status)
	// string "pat"
	o = append(o, 0xa3, 0x70, 0x61, 0x74)
	o = msgp.AppendInt64(o, z.ProcessedAt)
	// string "msg"
	o = append(o, 0xa3, 0x6d, 0x73, 0x67)
	o = msgp.AppendString(o, z.Message)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *OrderRes) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "oid":
			z.OrderID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "OrderID")
				return
			}
		case "f":
			z.From, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "From")
				return
			}
		case "status":
			z.Status, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "pat":
			z.ProcessedAt, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ProcessedAt")
				return
			}
		case "msg":
			z.Message, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Message")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *OrderRes) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len(z.OrderID) + 2 + msgp.StringPrefixSize + len(z.From) + 7 + msgp.StringPrefixSize + len(z.Status) + 4 + msgp.Int64Size + 4 + msgp.StringPrefixSize + len(z.Message)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *OrderService) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z OrderService) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 0
	_ = z
	err = en.Append(0x80)
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z OrderService) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 0
	_ = z
	o = append(o, 0x80)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *OrderService) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z OrderService) Msgsize() (s int) {
	s = 1
	return
}
