// Code generated by gencrpcserverv3. DO NOT EDIT.
package main

import (
	"context"
	"errors"

	"github.com/ndsky1003/crpc/v3/coder"
	"github.com/ndsky1003/crpc/v3/example/dto"
)

func (c *MyStructService) HandleMsg(ctx context.Context, method string, metaCoderT coder.T, reqCoderT coder.T, metaData, bodyData any) (any, error) {
	switch method {
	case "Full":
		// 1. 准备 Req
		var req dto.Req

		if b, ok := bodyData.([]byte); ok {
			// 远程调用 (Bytes)
			if len(b) > 0 {
				if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
					return nil, err
				}
			}
		} else if bodyData != nil {
			// 本地调用 (Object)
			if v, ok := bodyData.(*dto.Req); ok {
				if v != nil {
					req = *v
				}
			} else if v, ok := bodyData.(dto.Req); ok {
				req = v
			} else {
				return nil, errors.New("local call type mismatch for Full arg: req")
			}
		}

		// 2. 准备 Meta
		var meta dto.Meta
		if b, ok := metaData.([]byte); ok {
			if len(b) > 0 {
				if err := coder.Unmarshal(metaCoderT, b, &meta); err != nil {
					return nil, err
				}
			}
		} else if metaData != nil {
			if v, ok := metaData.(*dto.Meta); ok {
				if v != nil {
					meta = *v
				}
			} else if v, ok := metaData.(dto.Meta); ok {
				meta = v
			} else {
				return nil, errors.New("local call type mismatch for Full arg: meta")
			}
		}

		// 3. 调用方法
		res, err := c.Full(ctx, &meta, &req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	case "CtxReqPtr":
		// 1. 准备 Req
		var req dto.Req

		if b, ok := bodyData.([]byte); ok {
			// 远程调用 (Bytes)
			if len(b) > 0 {
				if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
					return nil, err
				}
			}
		} else if bodyData != nil {
			// 本地调用 (Object)
			if v, ok := bodyData.(*dto.Req); ok {
				if v != nil {
					req = *v
				}
			} else if v, ok := bodyData.(dto.Req); ok {
				req = v
			} else {
				return nil, errors.New("local call type mismatch for CtxReqPtr arg: req")
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res, err := c.CtxReqPtr(ctx, &req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	case "CtxReqVal":
		// 1. 准备 Req
		var req string

		if b, ok := bodyData.([]byte); ok {
			// 远程调用 (Bytes)
			if len(b) > 0 {
				if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
					return nil, err
				}
			}
		} else if bodyData != nil {
			// 本地调用 (Object)
			if v, ok := bodyData.(*string); ok {
				if v != nil {
					req = *v
				}
			} else if v, ok := bodyData.(string); ok {
				req = v
			} else {
				return nil, errors.New("local call type mismatch for CtxReqVal arg: req")
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res, err := c.CtxReqVal(ctx, req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return &res, nil
	case "MetaReq":
		// 1. 准备 Req
		var req dto.Req

		if b, ok := bodyData.([]byte); ok {
			// 远程调用 (Bytes)
			if len(b) > 0 {
				if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
					return nil, err
				}
			}
		} else if bodyData != nil {
			// 本地调用 (Object)
			if v, ok := bodyData.(*dto.Req); ok {
				if v != nil {
					req = *v
				}
			} else if v, ok := bodyData.(dto.Req); ok {
				req = v
			} else {
				return nil, errors.New("local call type mismatch for MetaReq arg: req")
			}
		}

		// 2. 准备 Meta
		var meta dto.Meta
		if b, ok := metaData.([]byte); ok {
			if len(b) > 0 {
				if err := coder.Unmarshal(metaCoderT, b, &meta); err != nil {
					return nil, err
				}
			}
		} else if metaData != nil {
			if v, ok := metaData.(*dto.Meta); ok {
				if v != nil {
					meta = *v
				}
			} else if v, ok := metaData.(dto.Meta); ok {
				meta = v
			} else {
				return nil, errors.New("local call type mismatch for MetaReq arg: meta")
			}
		}

		// 3. 调用方法
		res, err := c.MetaReq(&meta, &req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	case "ReqOnly":
		// 1. 准备 Req
		var req dto.Req

		if b, ok := bodyData.([]byte); ok {
			// 远程调用 (Bytes)
			if len(b) > 0 {
				if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
					return nil, err
				}
			}
		} else if bodyData != nil {
			// 本地调用 (Object)
			if v, ok := bodyData.(*dto.Req); ok {
				if v != nil {
					req = *v
				}
			} else if v, ok := bodyData.(dto.Req); ok {
				req = v
			} else {
				return nil, errors.New("local call type mismatch for ReqOnly arg: req")
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res, err := c.ReqOnly(&req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	case "ResOnly":
		// 1. 准备 Req
		var req dto.Req

		if b, ok := bodyData.([]byte); ok {
			// 远程调用 (Bytes)
			if len(b) > 0 {
				if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
					return nil, err
				}
			}
		} else if bodyData != nil {
			// 本地调用 (Object)
			if v, ok := bodyData.(*dto.Req); ok {
				if v != nil {
					req = *v
				}
			} else if v, ok := bodyData.(dto.Req); ok {
				req = v
			} else {
				return nil, errors.New("local call type mismatch for ResOnly arg: req")
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res := c.ResOnly(&req)

		// 4. 处理返回值
		return res, nil
	case "ErrOnly":
		// 1. 准备 Req
		var req dto.Req

		if b, ok := bodyData.([]byte); ok {
			// 远程调用 (Bytes)
			if len(b) > 0 {
				if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
					return nil, err
				}
			}
		} else if bodyData != nil {
			// 本地调用 (Object)
			if v, ok := bodyData.(*dto.Req); ok {
				if v != nil {
					req = *v
				}
			} else if v, ok := bodyData.(dto.Req); ok {
				req = v
			} else {
				return nil, errors.New("local call type mismatch for ErrOnly arg: req")
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		err := c.ErrOnly(&req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return nil, nil
	case "NoReturn":
		// 1. 准备 Req
		var req dto.Req

		if b, ok := bodyData.([]byte); ok {
			// 远程调用 (Bytes)
			if len(b) > 0 {
				if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
					return nil, err
				}
			}
		} else if bodyData != nil {
			// 本地调用 (Object)
			if v, ok := bodyData.(*dto.Req); ok {
				if v != nil {
					req = *v
				}
			} else if v, ok := bodyData.(dto.Req); ok {
				req = v
			} else {
				return nil, errors.New("local call type mismatch for NoReturn arg: req")
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		c.NoReturn(&req)

		// 4. 处理返回值
		return nil, nil
	case "Empty":
		// 1. 准备 Req

		// 2. 准备 Meta

		// 3. 调用方法
		c.Empty()

		// 4. 处理返回值
		return nil, nil
	case "CtxOnly":
		// 1. 准备 Req

		// 2. 准备 Meta

		// 3. 调用方法
		c.CtxOnly(ctx)

		// 4. 处理返回值
		return nil, nil
	default:
		return nil, errors.New("unknown method: " + method)
	}
}
