// Code generated by gencrpcserverv3. DO NOT EDIT.
package main

import (
	"context"
	"errors"

	"github.com/ndsky1003/crpc/v3/coder"
	"github.com/ndsky1003/crpc/v3/example/dto"
)

func (c *BusinessService) HandleMsg(ctx context.Context, method string, metaCoderT coder.T, reqCoderT coder.T, metaData, bodyData any, fromNetwork bool) (any, error) {
	switch method {
	case "QueryUser":
		// 1. 准备 Req
		var req dto.BusinessReq

		if fromNetwork {
			// 远程调用 (Bytes)
			if b, ok := bodyData.([]byte); ok {
				if len(b) > 0 {
					if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
						return nil, err
					}
				}
			}
		} else {
			// 本地调用 (Object)
			if bodyData != nil {
				if v, ok := bodyData.(*dto.BusinessReq); ok {
					if v != nil {
						req = *v
					}
				} else if v, ok := bodyData.(dto.BusinessReq); ok {
					req = v
				} else {
					return nil, errors.New("local call type mismatch for QueryUser arg: req")
				}
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res, err := c.QueryUser(ctx, &req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	case "UpdateUser":
		// 1. 准备 Req
		var req dto.BusinessReq

		if fromNetwork {
			// 远程调用 (Bytes)
			if b, ok := bodyData.([]byte); ok {
				if len(b) > 0 {
					if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
						return nil, err
					}
				}
			}
		} else {
			// 本地调用 (Object)
			if bodyData != nil {
				if v, ok := bodyData.(*dto.BusinessReq); ok {
					if v != nil {
						req = *v
					}
				} else if v, ok := bodyData.(dto.BusinessReq); ok {
					req = v
				} else {
					return nil, errors.New("local call type mismatch for UpdateUser arg: req")
				}
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res, err := c.UpdateUser(ctx, &req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	case "QueryOrders":
		// 1. 准备 Req
		var req dto.BusinessReq

		if fromNetwork {
			// 远程调用 (Bytes)
			if b, ok := bodyData.([]byte); ok {
				if len(b) > 0 {
					if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
						return nil, err
					}
				}
			}
		} else {
			// 本地调用 (Object)
			if bodyData != nil {
				if v, ok := bodyData.(*dto.BusinessReq); ok {
					if v != nil {
						req = *v
					}
				} else if v, ok := bodyData.(dto.BusinessReq); ok {
					req = v
				} else {
					return nil, errors.New("local call type mismatch for QueryOrders arg: req")
				}
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res, err := c.QueryOrders(ctx, &req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	case "CreateOrder":
		// 1. 准备 Req
		var req dto.BusinessReq

		if fromNetwork {
			// 远程调用 (Bytes)
			if b, ok := bodyData.([]byte); ok {
				if len(b) > 0 {
					if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
						return nil, err
					}
				}
			}
		} else {
			// 本地调用 (Object)
			if bodyData != nil {
				if v, ok := bodyData.(*dto.BusinessReq); ok {
					if v != nil {
						req = *v
					}
				} else if v, ok := bodyData.(dto.BusinessReq); ok {
					req = v
				} else {
					return nil, errors.New("local call type mismatch for CreateOrder arg: req")
				}
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res, err := c.CreateOrder(ctx, &req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	case "SearchProducts":
		// 1. 准备 Req
		var req dto.BusinessReq

		if fromNetwork {
			// 远程调用 (Bytes)
			if b, ok := bodyData.([]byte); ok {
				if len(b) > 0 {
					if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
						return nil, err
					}
				}
			}
		} else {
			// 本地调用 (Object)
			if bodyData != nil {
				if v, ok := bodyData.(*dto.BusinessReq); ok {
					if v != nil {
						req = *v
					}
				} else if v, ok := bodyData.(dto.BusinessReq); ok {
					req = v
				} else {
					return nil, errors.New("local call type mismatch for SearchProducts arg: req")
				}
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res, err := c.SearchProducts(ctx, &req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	case "GetProductDetail":
		// 1. 准备 Req
		var req dto.BusinessReq

		if fromNetwork {
			// 远程调用 (Bytes)
			if b, ok := bodyData.([]byte); ok {
				if len(b) > 0 {
					if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
						return nil, err
					}
				}
			}
		} else {
			// 本地调用 (Object)
			if bodyData != nil {
				if v, ok := bodyData.(*dto.BusinessReq); ok {
					if v != nil {
						req = *v
					}
				} else if v, ok := bodyData.(dto.BusinessReq); ok {
					req = v
				} else {
					return nil, errors.New("local call type mismatch for GetProductDetail arg: req")
				}
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res, err := c.GetProductDetail(ctx, &req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	case "GetCart":
		// 1. 准备 Req
		var req dto.BusinessReq

		if fromNetwork {
			// 远程调用 (Bytes)
			if b, ok := bodyData.([]byte); ok {
				if len(b) > 0 {
					if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
						return nil, err
					}
				}
			}
		} else {
			// 本地调用 (Object)
			if bodyData != nil {
				if v, ok := bodyData.(*dto.BusinessReq); ok {
					if v != nil {
						req = *v
					}
				} else if v, ok := bodyData.(dto.BusinessReq); ok {
					req = v
				} else {
					return nil, errors.New("local call type mismatch for GetCart arg: req")
				}
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res, err := c.GetCart(ctx, &req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	case "UpdateCart":
		// 1. 准备 Req
		var req dto.BusinessReq

		if fromNetwork {
			// 远程调用 (Bytes)
			if b, ok := bodyData.([]byte); ok {
				if len(b) > 0 {
					if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
						return nil, err
					}
				}
			}
		} else {
			// 本地调用 (Object)
			if bodyData != nil {
				if v, ok := bodyData.(*dto.BusinessReq); ok {
					if v != nil {
						req = *v
					}
				} else if v, ok := bodyData.(dto.BusinessReq); ok {
					req = v
				} else {
					return nil, errors.New("local call type mismatch for UpdateCart arg: req")
				}
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res, err := c.UpdateCart(ctx, &req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	case "BatchQuery":
		// 1. 准备 Req
		var req dto.BusinessReq

		if fromNetwork {
			// 远程调用 (Bytes)
			if b, ok := bodyData.([]byte); ok {
				if len(b) > 0 {
					if err := coder.Unmarshal(reqCoderT, b, &req); err != nil {
						return nil, err
					}
				}
			}
		} else {
			// 本地调用 (Object)
			if bodyData != nil {
				if v, ok := bodyData.(*dto.BusinessReq); ok {
					if v != nil {
						req = *v
					}
				} else if v, ok := bodyData.(dto.BusinessReq); ok {
					req = v
				} else {
					return nil, errors.New("local call type mismatch for BatchQuery arg: req")
				}
			}
		}

		// 2. 准备 Meta

		// 3. 调用方法
		res, err := c.BatchQuery(ctx, &req)

		// 4. 处理返回值
		if err != nil {
			return nil, err
		}
		return res, nil
	default:
		return nil, errors.New("unknown method: " + method)
	}
}
